### ISSUE TITLE
Create dockerhub repository for 'open-service-broker-azure'

### ISSUE THREAD

**Issue by arschles** [Azure/open-service-broker-azure#100]
After https://github.com/Azure/open-service-broker-azure/pull/91, the name of this project will have changed from `azure-service-broker' to 'open-service-broker-azure'. 

We need to create the newly named repo and update to push to it. We'll also need to change the chart in [Azure/helm-charts](https://github.com/azure/helm-charts) to point to the image in the new repository.

cc/ @jeremyrickard

**Comment by krancour** [comment]
Deferring this since we don't yet have the repo name we wanted. i.e. Just removing it from the v0.5.0 milestone.

**Comment by krancour** [comment]
I'm closing this for now. We'll re-open if we need to.
