### ISSUE TITLE
Quickstart failing on Minikube due to kubernetes/minikube#2256

### ISSUE THREAD

**Issue by MikkelHegn** [Azure/open-service-broker-azure#122]
When installing the Workdpress chart on Minikube, I run in to the issue descirbed here: kubernetes/minikube#2256.

The proposed change to manually create the directory ~~and change permission~~, seems to get around the volume issue.

1. Install the chart
2. Create the directory manually in the minikube VM
3. Delete the first pod that was created

This ends up in a new state where another issue with missing secrets, which I guess is because the Azure resources ends up not being provisioned.

Error: secrets "quickstart-wordpress-mysql-secret" not found
Error syncing pod

**Comment by MikkelHegn** [comment]
The secret error is caused by the chart not supporting the embedded MariaDB option.

**Comment by krancour** [comment]
The workaround seems like it might distract from what we're trying to emphasize-- which is the simplicity with which complex things backed by services in Azure can be deployed to k8s.

I need to look at this chart, but it might have an option to disable this volume mount (and just use ephemeral disk). Maybe that option can be set in the walkthrough. We'll definitely figure _something_ out to get around this.

> This ends up in a new state where another issue with missing secrets, which I guess is because
> the Azure resources ends up not being provisioned.
>
> Error: secrets "quickstart-wordpress-mysql-secret" not found
> Error syncing pod

This is normal. The secret in question isn't created until the MySQL instance is provisioned and bound to. When those things complete, the whole deployment eventually reaches a consistent state.

**Comment by MikkelHegn** [comment]
Thanks @krancour - however I never got to a state where I See any calls to the OSBA web-api or deployments in Azure. Maybe because of the pod deployment error.

**Comment by krancour** [comment]
@MikkelHegn can you try this and let me know if it improves your experience? I'm doing the same right now:

```
helm install azure/wordpress --name quickstart --namespace quickstart --set persistence.enabled=false
```

**Comment by MikkelHegn** [comment]
Yes - this works. I know have to look into OSBA and Azure issue with auth :-)

I see this in the OSBA:

time="2017-12-05T23:56:20Z" level=error msg="error executing job" error="error executing provisioning step \"deployARMTemplate\" for instance \"[GUID]\": error executing provisioning step: error deploying ARM template: error deploying \"[GUID]\" in resource group \"quickstart\": error getting deployment: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/[GUID]/resourcegroups/quickstart/providers/Microsoft.Resources/deployments/[GUID]?api-version=2016-09-01: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'" job=provisionStep taskID=[GUID]

**Comment by krancour** [comment]
Ok... the above worked out for me.
