### ISSUE TITLE
Spike: Expanded catalog of sqldb services

### ISSUE THREAD

**Issue by krancour** [Azure/open-service-broker-azure#124]
It's clear (based on user feedback) that wrt sqldb, not everyone wants to provision a new server and a single database upon that server. (One can see where this could get expensive. One would also bump into their quota pretty quickly.)

@zhongyi-zhang (iirc) had anticipated this and built in support for the following:

- New SQL Servers can be created "out of band" by an administrator (e.g. using `az` CLI or the portal).
- Details of such servers are outlined in a JSON doc, the content of which can be set as an environment variable to the broker.
- Broker is restarted.
- Provisioning requests for sqldb can include an optional parameter that is a logical name that references the configuration for one of the existing SQL Servers.

The thing that is problematic about this is there is too much that is done "out of band," which undermines the goal of providing seamless, platform-native workflows for provisioning services.

This issue proposes an alternative to this approach that I'd like to explore.

First, note that these circumstances aren't isolated to sqldb. It's equally possible that users may wish to provision a Postgres or MySQL server and _then_ provision multiple databases upon that server. Storage accounts: One may wish to provision a storage account _then_ multiple containers within. Event hubs and service buses: One may wish to provision a namespace _then_ multiple hubs or buses within. Generalizing, there are many services that involve a hierarchy of resources wherein one might wish to provision and manage the lifecycle of some "parent" or "container" resource separately from multiple "subordinate" or "child" resources.

Note: Despite this generality, the sqldb module is the only one that acknowledges this today (even if the implementation is, possibly, not ideal).

Using sqldb as a guinea pig, I'd like to explore the following:

- Expand the services offered by the sqldb module from one to three:
    - "All in one": Same as the default behavior today. You get a new SQL Server and _one_ new database on that server. Plans of this service are all tiers of SQL Server.
    - "Server only": Provisions a SQL Server only-- no database. A required parameter will be a user-provided identifier that can later be used to reference this server. Plans of this service are all tiers of SQL Server.
    - "Database only": Provisions a database on an existing server. The server on which to provision the database is identified through a required parameter that references an existing server. There is only one plan for this service.

This might requires some architectural changes to the broker itself to make it start to understand parent/child relationships between service instances.

Lastly, I'll call out an interesting use case where a user might request a new instance of a "parent" or "container" service (like a SQL Server) _and_ simultaneously a new "child" or "subordinate" service (like a database). This could happen in a Helm chart, for instance. Again, we'll need to make the broker understand these sort of relationships-- at least well enough that provisioning of child / subordinate services can be deferred until their parent is fully provisioned.

This is a spike because I can't foresee exactly how this is going to pan out, but I believe this is a useful exercise to undertake in order to learn how our overall catalog of services and our architecture both need to evolve to support a wider array of use cases than we had in mind initially.

**Comment by zhongyi-zhang** [comment]
>Expand the services offered by the sqldb module from one to three: 
"All in one": Same as the default behavior today. You get a new SQL Server and one new database on that server. Plans of this service are all tiers of SQL Server.
"Server only": Provisions a SQL Server only-- no database. A required parameter will be a user-provided identifier that can later be used to reference this server. Plans of this service are all tiers of SQL Server.
"Database only": Provisions a database on an existing server. The server on which to provision the database is identified through a required parameter that references an existing server. There is only one plan for this service.

@krancour, I need to mention two things here: 
1. SQL DB is billed based on database (which is different from MySQL&PostgreSQL billed based on instance(server)). So the services which create new database should have all the tiers. SQL Server is free. And it's usual to configure TDE, threat detection, and auditing at server level. Then its databases just inherit these properties.
2. For "Database only", do you mean writing the server credentials (included RG/location/server name/admin/admin password) in required parameter instead in env vars? This might not satisfy some companies which have strict policy (such as the customer who firstly requested MASB to support existing server scenario). Their developers should not have the privilege to manage the server. They just want that "I am going to create a database on a server managed by the operator". So the server credentials should not occur in required parameters. The current design in existing server scenario is good for them.

**Comment by krancour** [comment]
@zhongyi-zhang thanks for info in no. 1. I will adjust accordingly.

Re: no. 2: I hear you loud and clear on the requirement that you've heard from many customers. I do believe it's a legitimate use case. That said, we've heard from other customers that they'd like this supported without having to step outside a platform-native workflow... so these two use cases are at odds. Let's see what we can do about supporting both scenarios.

**Comment by krancour** [comment]
I should add also that the bit about developers managing databases only but not servers is a use case that I think can (eventually) be facilitated with the model I described-- at least when k8s is the platform (won't be surprised if CF keeps pace). There has been talk of managing permissions re: who can provision what. So in the model I described, I imagine cluster admins that provision servers via platform native workflows then developers provision (only) databases on existing servers with no option to provision new servers of their own.

**Comment by zhongyi-zhang** [comment]
@krancour wow, that's great. Expect your following works! Please add me as one of the reviewers.

**Comment by zhongyi-zhang** [comment]
@krancour @jeremyrickard I am following up with your progress on the feature branch. From my understanding, the existing server scenario I mentioned above will be two service instances in the new design, a server only instance as parent and a database only instance, right? This is nice for new broker users.
On the other hand, SQLDB will be one of the services we don't support to directly migrate from MASB to OSBA. In broker storage side, the migration script can be wrote to split one MASB instance record into two and translate to OSBA style. But in the Cloud Controller (which saves the catalog in CF) database side, I am afraid it's not feasible to do that.
That's ok for me, just to confirm.

**Comment by krancour** [comment]
This should have been closed by #243
