### ISSUE TITLE
The environment name of basic authentication is not same with meta-azure-service-broker

### ISSUE THREAD

**Issue by bingosummer** [Azure/open-service-broker-azure#129]
In open-service-broker-azure, the environment names are:
```
BASIC_AUTH_USERNAME
BASIC_AUTH_PASSWORD
```

In meta-azure-service-broker, the environment names are:
```
SECURITY_USER_NAME
SECURITY_USER_PASSWORD
```
These names are required for Pivotal Cloud Foundry. Please refer to https://docs.pivotal.io/tiledev/1-12/tile-generator.html#packages.
```
Your broker is automatically registered with the Cloud Controller. The Cloud Controller invokes your broker’s endpoints, and it uses basic authentication to secure those API calls. The credentials it uses are passed to your broker in two environment variables:

SECURITY_USER_NAME
SECURITY_USER_PASSWORD
Your broker is expected to accept those credentials. If it doesn’t, automatic broker registration fails.
```

Is it possible to change to `SECURITY_USER_NAME` and `SECURITY_USER_PASSWORD`? Thanks.

**Comment by bingosummer** [comment]
CC: @arschles @krancour @zhongyi-zhang

**Comment by zhongyi-zhang** [comment]
@krancour this change allows us to publish PCF tile for OSBA as the successor of MASB in https://network.pivotal.io/products/azure-service-broker. It helps to get into Pivotal's ecosystem, as Pivotal is such a big customer and PCF users prefer to install a tile rather than open source release.
I'll work on building the tile if we do this change.

**Comment by krancour** [comment]
@bingosummer @zhongyi-zhang thanks for raising this issue. I just wanted to respond quickly and let you know I wasn't ignoring it. Need to sync with @arschles about this, but it's on the radar now. Thanks!

**Comment by zhongyi-zhang** [comment]
@arschles @krancour any update on this? Thanks!

**Comment by krancour** [comment]
We still need to talk it over. I will have an answer for this in the v0.6.0 (end of January) timeframe.
