### ISSUE TITLE
Bound users in postgres should be in azure_pg_admin role

### ISSUE THREAD

**Issue by arschles** [Azure/open-service-broker-azure#16]
_From @krancour on September 28, 2017 20:17_

Without this, users cannot enable extensions, and the inability to do so rules out too many common use cases. (i.e. There's too much off the shelf software that requires various postgres extensions. GitLab CE is a great example.)

Unfortunately, this is not easily accomplished at this time because, while it _is_ possible to assign new users to the `azure_pg_admin`, one must be a superuser to revoke the role. And even the administrative user is not a superuser. Inability to revoke the role from a bound user means it is also impossible to drop a user upon unbind since a `drop role` (user) command implicitly drops all the role's (user's) roles (group's).

(PostgreSQL uses "role" too much. 😛 )

**Comment by yves-vogl** [comment]
> Note that this issue impacts the [Gitlab CE chart](https://github.com/deis/service-catalog-charts/pull/3), so it would be helpful to figure it out sooner rather than later

How did you solve this?

**Comment by krancour** [comment]
@yves-vogl see #51. I instead of handing out near-superuser level of access upon bind, the provisioning parameters were expanded to permit the party requesting provisioning to specify what extensions are needed. These get pre-installed by the broker upon provisioning.
