### ISSUE TITLE
Use an OSBA-specific user-agent string for calls to ARM RPs

### ISSUE THREAD

**Issue by seanmck** [Azure/open-service-broker-azure#170]
The latest recommendation from the BI v-team is to use user-agent for tracking the provenance of client-side requests to Azure RPs. Unlike tags, it is already present in the ARM Kusto data store, which makes it easy to wire up with PowerBI.

Suggest we do something like:

open-service-broker-azure/version

**Comment by arschles** [comment]
The MSFT Go SDK team also requested we do this
