### ISSUE TITLE
Created MySQL user missing the EXECUTE privilege 

### ISSUE THREAD

**Issue by sabbour** [Azure/open-service-broker-azure#197]
The created MySQL user is missing the ALL privilege.

I was under the impression that the user created here would have the same privileges as the default "azureuser". This is not the case as per the line below.
https://github.com/Azure/open-service-broker-azure/blob/60b1bb7940b5093c353dc1ecab3de0bf8386186c/pkg/services/mysqldb/bind.go#L55

For a user that is created with this, they will not have enough permissions to do the below, which is supported scenario in the documentation (https://docs.microsoft.com/en-us/azure/mysql/howto-create-users)

```
CREATE DATABASE testdb;
CREATE USER 'db_user'@'%' IDENTIFIED BY 'StrongPassword!';
GRANT ALL PRIVILEGES ON testdb . * TO 'db_user'@'%'; # <- ERROR 1044 (42000): Access denied for user 'vs9uigqscy'@'%' to database 'testdb'
FLUSH PRIVILEGES;
```

This breaks applications (for example, the Magento Helm chart).

**Comment by krancour** [comment]
@sabbour at a glance, this may seem like a mistake, but it's deliberate. Right now, when you provision a MySQL db through the broker, you're getting a MySQL _server_ and a single db _on_ that server. We anticipate soon having the option to provision multiple databases on a single server. This being the case, it's not a valid or safe assumption that any given application that has bound to some MySQL database should have administrator level privileges-- as that will grant them unrestricted access to not only their own database, but to others as well.

> CREATE DATABASE testdb;
CREATE USER 'db_user'@'%' IDENTIFIED BY 'StrongPassword!';
GRANT ALL PRIVILEGES ON testdb . * TO 'db_user'@'%'; # <- ERROR 1044 (42000): Access denied for user 'vs9uigqscy'@'%' to database 'testdb'
FLUSH PRIVILEGES;

We don't believe these are commands that a user (including an application) should be issuing. Creating _new_ databases and users _of_ that database is the broker's job-- not that of a user or application. This being said, we've certainly encountered these cases before where some "off the shelf" software wants broad, unrestricted access to the entire RDBMS to set itself up by creating its own DB, login, etc. Strong opinion-- that's not ideal and applications that do that are in the wrong for doing so.

Let me defend that last opinion. Rewinding a few years to when I was in an ops/SRE role, if a developer told me that their application needed admin access to a multi-tenant database, I'd have told them no way. If a human operator would not have endorsed such a request on security grounds, neither should the broker.

Does this make some sort of sense?

**Comment by sabbour** [comment]
@krancour Actually when Helm runs the chart multiple times, I get multiple databases provisioned on the same server, each with its own username and password.

As to your point whether these commands should be issued by the application or not, they are actually issued by the Bitnami Magneto Helm chart. This is how it works when it is using MariaDB containers created on the cluster, and I was trying to create a new chart that uses the OSBA and it fails due to this specific problem.

I do agree with you that an application should not have root access. However, the Bitnami installer is actually creating a database for Magento, creating a user for this database and trying to grant this user ALL privileges to this database only.

How shall we address this in your opinion? This is not something we can control, and the chart will simply fail to install.

**Comment by krancour** [comment]
Ok. So it sounds like it's not Magento itself doing this, but some aspect of the existing Magento chart created by Bitnami, yes?

Bitnami has actually be very cooperative with us, to date, in modifying their images (for many different pieced of software) and (upstream) charts in ways that make them work more easily with existing dbs. This has been an often-asked for feature from them. It seems, perhaps, Magento simply hasn't received this treatment yet.

Here's an example of such an ask for WordPress: https://github.com/kubernetes/charts/issues/1727 Similar requests exist (or have already been implemented for) Drupal and others.

btw... "existing" database, in our case, could simply mean one managed by the broker.

Your best bet is to open an issue in the upstream charts repo. One of the repo maintainers is from Bitnami and you'll likely hear something from him pretty quickly.

**Comment by sabbour** [comment]
@krancour sorry it seems I edited the comment while you were replying. Magento's installation documentation is explicitly asking to use **ALL PRIVILEGES**. See: http://devdocs.magento.com/guides/v2.0/install-gde/install/hosted/hosted_start_db.html

**Comment by sabbour** [comment]
Should we make it configurable via bindingParameters maybe, instead of hardcoding it?

**Comment by krancour** [comment]
Looking at the Magento docs you just pointed me to...

These directions for adding a db, user, user permissions etc. _via gui_ do seem to presume that Magento already has unrestricted (i.e. admin) access to the RDBMS so that it can _create_ that database, user, etc. My gut says that this can't be the _only_ way to setup Magento. If it were, lots of ops-ish things wouldn't be possible, like scripting the setup, restoring Magento from an existing database, etc. I'm not an expert on Magento,  by any means, but is there not some config file where you can point this at an existing database?

> Should we make it configurable via bindingParameters maybe, instead of hardcoding it?

What "it" is here. Whether the bound user is an admin or not? We definitely cannot relax security for the sake of making a certain application work.

**Comment by sabbour** [comment]
"it" here refers to the privileges string.

**Comment by krancour** [comment]
@sabbour we'll look at this. Thanks!

**Comment by jeremyrickard** [comment]
Hey @sabbour, any chance you have your helm chart in a state you could open a PR so i could grab it and test this change out?

**Comment by sabbour** [comment]
@jeremyrickard I didn't the chart beyond that step but I suppose it should work.
Do you want me to create a PR for this now?

**Comment by sabbour** [comment]
It worked. Thanks!

**Comment by jeremyrickard** [comment]
@sabbour thank you for validating the change we have in flight! I'll get it merged today and close this out!
