### ISSUE TITLE
Meta: Modules need to cover wider variety of use cases

### ISSUE THREAD

**Issue by arschles** [Azure/open-service-broker-azure#20]
_From @krancour on September 28, 2017 2:35_

This issue is a placeholder for the moment.

To tease the discussion, see the below comments.

The sentiments expressed in those comments are likely applicable to a variety of existing modules, including, but probably not limited to:

* PostgreSQL
* MySQL
* SQL Server

**Comment by krancour** [comment]
I'm going to close this because #124 is the issue that's really allowing us to explore the ideas expressed i this issue. There's no sense keeping this one open if they're (virtually) duplicates.
