### ISSUE TITLE
Proposal: Kill two birds with one stone-- expand lifecycle tests into e2e tests

### ISSUE THREAD

**Issue by krancour** [Azure/open-service-broker-azure#224]
The entry point for executing the service lifecycle tests is currently the aync engine. i.e. HTTP requests, request validation, etc. are not involved. These effectively test "from the engine on down," but fall short of being real e2e tests.

Rather than add a separate suite of tests, I want to propose that we amend the current suite of lifecycle tests to _become_ e2e.

@jeremyrickard any thoughts?

**Comment by jeremyrickard** [comment]
I'm in favor of this. We're already testing the modules so we shouldn't do that twice. Adding the API layer to this should not impact the tests that much as the bulk of the time is consumed within the engine itself.  

When we do this, I think that we _should_ retain the ability to run these selectively (it has been super useful to me!)

**Comment by krancour** [comment]
> When we do this, I think that we should retain the ability to run these selectively

Absolutely. No question.

**Comment by krancour** [comment]
The PR implementing this has moved to v0.11.0. So too is this.

**Comment by krancour** [comment]
This should have been closed a long time ago. e2e tests have been present in this project for a long time.
