### ISSUE TITLE
Service catalog should return a sorted list of plans

### ISSUE THREAD

**Issue by ritazh** [Azure/open-service-broker-azure#267]
For example, this is defined by the service broker, in this case sort by DTUs: https://github.com/Azure/open-service-broker-azure/blob/master/pkg/services/mysqldb/catalog.go

**Comment by krancour** [comment]
It might not be obvious, but the catalog you're pointing to is sorted first by tier and _then_ by "size" (DTUs, in this case) within the tier. imo, DTUs are of secondary importance to tier because while you _can_ increase or decrease DTUs within a tier, you cannot move between tiers. i.e. Once you pick a tier, you're locked into it.

**Comment by arschles** [comment]
@krancour the service-catalog might not be sorting by anything that the broker returns? i.e. my thought is that when you do a `svcat get plans` the Kube API might be returning the `ClusterServicePlans` by their Kube resource names, which are UUIDs.

Thoughts?

**Comment by krancour** [comment]
@arschles I'm fairly certain that is the case.

**Comment by krancour** [comment]
So is this an issue for kubernetes-incubator/service-catalog instead?

**Comment by ritazh** [comment]
I can create the issue there, just wanted to make sure this is a catalog issue, not the broker.

**Comment by jeremyrickard** [comment]
I opened an issue for svcat to sort (i'm working on it this week). 

See https://github.com/kubernetes-incubator/service-catalog/issues/1703

**Comment by ritazh** [comment]
@jeremyrickard I think it's great to have svcat return a sorted list...I was thinking more at the api level so when we query the api, it would return the sorted list of plans as implemented by the broker.

**Comment by krancour** [comment]
It's still not clear to us what value this provides at the broker level and we're also not really sure how we'd implement it. Closing.
