### ISSUE TITLE
Enhance MongoDB API CosmosDB Service Binding

### ISSUE THREAD

**Issue by jeremyrickard** [Azure/open-service-broker-azure#282]
We should enhance the CosmosDB binding information in line with #275. See https://cloud.spring.io/spring-cloud-connectors/spring-cloud-cloud-foundry-connector.html and https://docs.cloudfoundry.org/services/binding-credentials.html. Also see the azure lib: https://github.com/Microsoft/azure-spring-boot/blob/master/azure-spring-boot/src/main/java/com/microsoft/azure/spring/cloundfoundry/environment/VcapResult.java

The MongoDB API service should return the uri string starting with mongodb://<user>:<pass>@<host>:<port>

**Comment by krancour** [comment]
@jeremyrickard is this still outstanding? Feel like this was addressed.

**Comment by jeremyrickard** [comment]
@krancour I have a PR ready for it but had forgotten to submit it for v0.10.0, hence the move to v0.11.0. 
Will have it opened up on Monday for review :)

**Comment by jeremyrickard** [comment]
I updated this issue to be specific to MongoDB. The DocumentDB thing doesn't make sense unless we add a an actual database to the database account.
