### ISSUE TITLE
final lifecycle test cleanup should produce output at intervals

### ISSUE THREAD

**Issue by krancour** [Azure/open-service-broker-azure#289]
Individual tests prevent Circle from timing out by producing output every minute to state they're still in-progress. When all tests are complete and final cleanup begins, there is no more guaranteed output at regular intervals. This means if final cleanup takes a long time, Circle could timeout before it completes and never show us the result of all the test cases that just ran.

We should make the cleanup produce output at regular intervals.

Alternatively, we could consider initiating cleanup without waiting for it to complete? The only issue with this may be that tests having completed then does not offer us any assurance that resources used by the test have been freed. I'd like that assurance since we can only run a couple instances of the lifecycle tests concurrently without hitting our quotas.

The ideal (which might be more difficult than we're willing to work for while having other higher priority items) might be to guarantee that we see test output first and _then_ wait for cleanup to complete.

@jeremyrickard any thoughts on this? I'm happy to implement. Putting this in v0.9.0, because this is basically a test-flake and it's slowing us down a bit.

**Comment by jeremyrickard** [comment]
Closed by #291
