### ISSUE TITLE
CosmosDB - Add support for geo-redundancy

### ISSUE THREAD

**Issue by julienstroheker** [Azure/open-service-broker-azure#293]
Be able to choose the `geo-redundancy` option at the creation

![screen shot 2018-02-22 at 10 58 56 am](https://user-images.githubusercontent.com/8661347/36558301-710fc936-17bf-11e8-882c-52f46ce3db9a.png)

**Comment by jeremyrickard** [comment]
Thanks for the issue @julienstroheker. Looking at the ARM template we are using and the portal, that isn't a direct option like the portal, which defaults to East US and West US (based on the tool tip it gave me). In the ARM template, we can provide:

```
locations | -  An array that contains the georeplication locations enabled for the Cosmos DB account. 
-- | -- | -- | --
```

Do you think exposing that as a provisioning parameter is sufficient?

**Comment by julienstroheker** [comment]
@jeremyrickard Sound good !

**Comment by zhongyi-zhang** [comment]
Solved by https://github.com/Azure/open-service-broker-azure/pull/544.
