### ISSUE TITLE
Add the rest of MSSQL module features in MASB

### ISSUE THREAD

**Issue by arschles** [Azure/open-service-broker-azure#3]
_From @zhongyi-zhang on October 20, 2017 8:34_

* ~~Make enabling TDE optional~~ (krancour edit: splitting this into its own issue)
* Allow to update the service plan (via service broker update api)
* krancour edit: Others???

**Comment by krancour** [comment]
Let's break this into two issues.

**Comment by krancour** [comment]
Let's also track down whatever other features might have been implemented by MASB that are not on this list.

**Comment by zhongyi-zhang** [comment]
Thanks @krancour. There is one more: specify [connection policy](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connectivity-architecture). You can just see this line in OSBA code: https://github.com/Azure/open-service-broker-azure/blob/master/pkg/services/mssql/common.go#L21 
```
query.Add("TrustServerCertificate", "true")
```
We set `TrustServerCertificate` to `true`. In some scenarios strict security is required, it should be set to `false` and provide `hostNameInCertificate`. Here comes the issue: https://github.com/denisenkom/go-mssqldb/issues/288. And setting connection policy to proxy can solve it.
I only hit it with Go SQL client. Node client and Java client are both OK. It is a corner issue, I think. So I was not sure whether we should also support it in OSBA and didn't list it above... Appreciate your thoughts.

**Comment by zhongyi-zhang** [comment]
Features for MSSQL module are tracked in https://github.com/Azure/open-service-broker-azure/issues/566 for either the feature parity to MASB or new features. Close this one.
