### ISSUE TITLE
Handle errors more sanely

### ISSUE THREAD

**Issue by krancour** [Azure/open-service-broker-azure#303]
In general, we do a good job of error handling, but because errors in Go don't automatically convey information about the location (file and or function) of the error, we do a whole lot of (manually) wrapping errors with additional context like so:

```
if err := foo() {
  return fmt.Errorf("there was some kind of error doing foo: %s", err)
}
```

While the context is nicely human readable, this is still, perhaps not ideal. Doing this is laborious and verbose. When an error occurs, you pinpoint it by grepping the code for the human-readable context string. Yuck.

I started looking around for packages that will take some of the pain out of this, and [pkg/errors](https://github.com/pkg/errors) is what I've identified as a good candidate. It's widely used, has a friendly, permissive license, and is of known pedigree, having been created by Dave Cheney, who also wrote a few nice blog posts about this topic, including [this one](https://dave.cheney.net/2016/06/12/stack-traces-and-the-errors-package).

When time allows, I'd like to refactor much of the broker to utilize this. As appropriate (sparingly as possible), I want to decorate errors (mainly ones that do not originate within our own code) so that they include a stack trace. Where appropriate, errors can still be annotated with human-readable context, but the point is I want to move away from grepping for human-readable context strings as the only way to pinpoint where in our code an error has occurred.

**Comment by jeremyrickard** [comment]
👍  this seems like a great thing to do.

**Comment by arschles** [comment]
see https://godoc.org/github.com/pkg/errors
