### ISSUE TITLE
MS SQL: enable optional TDE

### ISSUE THREAD

**Issue by krancour** [Azure/open-service-broker-azure#325]
This issue is split from the broader #3 because we intend to address this in v0.10.0, while other (possibly as-yet-unidentified) features may be implemented later, as they are identified (and if there's value in doing so).

**Comment by jeremyrickard** [comment]
TDE is turned on be default:

```
All newly created SQL databases are encrypted by default by using service-managed transparent data encryption. Existing databases before May 2017 and databases created through restore, geo-replication, and database copy aren't encrypted by default.
```

per https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption-azure-sql so this is being added with a default value of true for backward compatibility.

**Comment by jeremyrickard** [comment]
@ritazh @zhongyi-zhang  I wanted to follow up on this issue.

TDE is enabled by default on Azure SQL databases. Do we have a really compelling use case for actually disabling it? I'm having issues with ARM disabling it at provision time:

**Comment by zhongyi-zhang** [comment]
@jeremyrickard Indeed, I never heard about a use case for actually disabling it.
Agree not to expose the parameter and just enable it. It would be not too late to expose it if someone shared a reasonable scenario to disable TDE.

**Comment by jeremyrickard** [comment]
Closing this. TDE is enabled by default, if people want to disable it we recommend they go to the portal and do it out of band
