### ISSUE TITLE
README instructions of installing Service Catalog CLI is outdated

### ISSUE THREAD

**Issue by akaroml** [Azure/open-service-broker-azure#334]
In README, the Service Catalog CLI installation instructions are outdated. It's now pointing to the original https://github.com/Azure/service-catalog-cli, which is deprecated. Following those instructions won't take you anywhere but waste your time.

The new installation instruction of svcat is here:
https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/install.md

Please make sure the documentation is up to date.

**Comment by carolynvs** [comment]
Thanks for bringing that up! 👍  I completely forgot to update this when I archived the original cli repo. I'll get that fixed.
