### ISSUE TITLE
Support multiple broker instances (different accounts)

### ISSUE THREAD

**Issue by berndtj** [Azure/open-service-broker-azure#343]
I'm trying to build a service which would manage services across accounts/tenants.  In order to do so, I need to create brokers on a per tenant basis on the same kubernetes cluster.  Currently, it appears that only one broker of a particular type is supported.  This may be a limitation of the kubernetes service catalog, not necessarily this broker.

**Comment by berndtj** [comment]
There are 2 issues that currently hamper this scenario:

1. hard-coded GUIDs in the service catalogs.
2. hard-coded broker name in the open-service-broker-azure chart.

I manually edited these and verify that two broker instances are possible.

**Comment by jeremyrickard** [comment]
@berndtj we're reviewing when to start implementing this, but as an FYI service-catalog is in the process of implementing namespaced brokers, classes and plans. I believe that will allow you to get the behavior you needed without any modifications.

**Comment by berndtj** [comment]
This is great news!  I'll have to check out the namespaced brokers.  FWIW, we are looking at providing services to a multi-tenanted service, ideally without requiring a separate service catalog deployment for each tenant (or org/group).  I'm not sure namespaced brokers will address all of our issues.

**Comment by krancour** [comment]
I'm sufficiently convinced that namespaces brokers in k8s will address the concern here, so I'm going to close this. If someone wants to try and change my mind about that, then I will certainly hear them out and reconsider.
