### ISSUE TITLE
Update readme to including Service Fabric sample

### ISSUE THREAD

**Issue by MikkelHegn** [Azure/open-service-broker-azure#348]
@Haishi2016 has helped release a sample to show how to implement a Service Catalog on Service Fabric. (That a few services :-))... https://github.com/Azure-Samples/service-fabric-service-catalog

I would like to suggest a pointer form the read.me file to this repo for discoverability.

**Comment by seanmck** [comment]
@MikkelHegn Feel free to submit a PR for this. :)
