### ISSUE TITLE
Double check / improve logic for obtaining cosmosdb connection strings

### ISSUE THREAD

**Issue by krancour** [Azure/open-service-broker-azure#349]
I found this odd bit of "legacy" code in the mongo provisioning process:

```
// Allow to remove the https:// and the port 443 on the FQDN
// This will allow to adapt the FQDN for Azure Public / Azure Gov ...
// Before :
// https://6bd965fd-a916-4c3c-9606-161ec4d726bf.documents.azure.com:443
// After :
// 6bd965fd-a916-4c3c-9606-161ec4d726bf.documents.azure.com
hostnameNoHTTPS := strings.Join(
	strings.Split(dt.FullyQualifiedDomainName, "https://"),
	"",
)
dt.FullyQualifiedDomainName = strings.Join(
	strings.Split(hostnameNoHTTPS, ":443/"),
	"",
)
sdt.ConnectionString = fmt.Sprintf(
	"mongodb://%s:%s@%s:10255/?ssl=true&replicaSet=globaldb",
	dt.DatabaseAccountName,
	sdt.PrimaryKey,
	dt.FullyQualifiedDomainName,
)
```

This looks odd.

1. I'm not sure why we should ever have to _adapt_ the FQDN, as reported by the ARM deployment, for other clouds. afaik, the FQDN should always be correct to begin with.
1. The logic that follows doesn't appear to have anything to do with no. 1, but rather with building a Mongo-friendly connection string.
1. There's an API for obtaining connection strings: https://docs.microsoft.com/en-us/rest/api/documentdbresourceprovider/databaseaccounts/listconnectionstrings#cosmosdbdatabaseaccountlistconnectionstringsmongo

While the logic for non-mongo cosmos accounts is simpler, I think it is also suspect.

Let's get this sorted out.

Assigning to @jeremyrickard as requested.

**Comment by sivethe** [comment]
The above logic is not correct for MongoDB 3.6 accounts which are hosted on a different FQDN.  Please use the listConnectionString RP api to get the connection strings for MongoDB accounts
