### ISSUE TITLE
Question on running multiple instances with same config

### ISSUE THREAD

**Issue by karataliu** [Azure/open-service-broker-azure#352]
We have the requirement for high availability so that we might run 2 or more service broker instances  with same config at same time. The config includes both `Azure relate config` and `back-end redis connection config`.

I've tried with 3 instances connecting to same redis db, and seems it work well so far.

The challenge would be whether there's possibility that 2 instances would do duplicate things? Say user requests a single storage service, but back-end happened to create two? 

Could someone please help shed some light on this case? Thanks.

**Comment by krancour** [comment]
@karataliu I'm sorry no one ever answered this. In case you still care about this, _all_ provisioning is accomplished asynchronously using the Redis "reliable queue" pattern. All tasks are guaranteed to be picked up by only a single worker. If that worker dies, its task will eventually be re-assigned to another worker and resumed.

There should be no possibility of two workers concurrently working on the same task.
