### ISSUE TITLE
Client and server share too much code

### ISSUE THREAD

**Issue by krancour** [Azure/open-service-broker-azure#357]
Currently, client code re-uses the following types that are used by the server-side:

- `service.Catalog`
- `api.ProvisioningRequest`
- `api.BindingRequest`
- `api.BindingResponse`
- `api.UpdatingRequest`

And the following exported constant:

- `api.OperationDeprovisioning`

Purely on philosophical grounds, I do not like this. (Admittedly, it's my own doing.) I would prefer that client code share nothing with server-side code. The reasoning is that eventually, we will wish to replace our client library with an existing one (such as [pmorie/go-open-service-broker-client](https://github.com/pmorie/go-open-service-broker-client), for instance) _or_, alternatively, extract our client code into its own project/library. In either of those cases, the effort will be reduced by ensuring client-side and server-side code share nothing.

**Comment by carolynvs** [comment]
If a user wanted to interact directly with osba, could they use paul's osba client today?
