### ISSUE TITLE
Error: apiVersion "servicecatalog.k8s.io/v1beta1" in open-service-broker-azure/templates/broker.yaml is not available

### ISSUE THREAD

**Issue by spacecat** [Azure/open-service-broker-azure#363]
...when running:

helm install azure/open-service-broker-azure --name osba --namespace osba \
    --set azure.subscriptionId=$AZURE_SUBSCRIPTION_ID \
    --set azure.tenantId=$AZURE_TENANT_ID \
    --set azure.clientId=$AZURE_CLIENT_ID \
    --set azure.clientSecret=$AZURE_CLIENT_SECRET

Any clues? 

Just following instructions from the docs btw:

https://docs.microsoft.com/en-us/azure/aks/integrate-azure#install-open-service-broker-for-azure
https://github.com/Azure/open-service-broker-azure/blob/master/docs/quickstart-aks.md

**Comment by jeremyrickard** [comment]
My guess on this is that your service catalog hasn't started up. I believe that error indicates that it doesn't know about the svc-cat resource types. 

Could you check the status of the Service Catalog pods? If you used the helm chart and the quickstart to install that, it should be in the "catalog" namespace.

**Comment by shayshahak** [comment]
i get the same issue and i followed the technical instruction doc exactly. how did you resolve this?
