### ISSUE TITLE
Move "parameter defaults" logic to types classes

### ISSUE THREAD

**Issue by jeremyrickard** [Azure/open-service-broker-azure#366]
With the change to how we are handling parameters, it would be good to move the logic of "default" parameter value setting to the types classes and make it closer to where it is defined. Currently, most of it is scattered throughout the module provision code.

**Comment by carolynvs** [comment]
I have no idea what's going on but it sounds like it's up my "defaulting all the things" alley. Is this related or am I just a dork? 😀

**Comment by krancour** [comment]
I think this was accomplished by #478
