### ISSUE TITLE
Update SQL Database Plans

### ISSUE THREAD

**Issue by jeremyrickard** [Azure/open-service-broker-azure#392]
The Azure SQL Database Plans seem to be out of date with what's in https://azure.microsoft.com/en-us/pricing/details/sql-database/managed

Should we update this to match current state @krancour @arschles? It looks like the DTU pricing is still available but it's _not_ what shows up if you load the page by default.

**Comment by zhongyi-zhang** [comment]
The problem is how to define plans for the core model. The flexibility of core-model pricing looks against these specified service plans, unless the broker can delegate the specification of plans to the cluster operator.

**Comment by jeremyrickard** [comment]
@zhongyi-zhang I think we can leave them as well for now and then deprecate them. I chatted with a PM from MySQL and PostgreSQL and she indicated that we were generally moving away from the DTU based pricing. OSB is specifically looking at a mechanism for adding deprecation to plans, so once that's a thing we can look at adding it to the catalog properly. This was more about adding those new plans to mirror what's there.  Mostly likely defining the three sku types and accepting the other bits as parameters, with defaults that match the portal now.

**Comment by zhongyi-zhang** [comment]
@jeremyrickard mirror plans sound good.

**Comment by jeremyrickard** [comment]
@zhongyi-zhang we are in the process of adding the newer plans for SQL Database. In the case of MySQL and PostgreSQL, the PM for those products wanted us to remove the older plans. For SQL Database, they need to keep the older plans around as well because the new vCore plans won't have sub-core capability that you can get with DTU based plans.

I'd like to propose we refactor the standard and premium plans to follow the same model and expose DTUs as a parameter (we have the ability to express allowed values using JSON Schema now so we can constrain it in docs and via schema/param validation) in order to simplify things a little more, so we maybe end up with:

plans:
basic
standard
premium
general-purpose (new vCore plan)
business-critical  (new vCore plan)

**Comment by zhongyi-zhang** [comment]
@jeremyrickard sounds good. Thanks for the info!
