### ISSUE TITLE
Create Bindings overwrites existing secrets 

### ISSUE THREAD

**Issue by codevulture** [Azure/open-service-broker-azure#404]
Creating the bindings overwrites the existing secrets stored in k8s

https://github.com/Azure/open-service-broker-azure/blob/master/docs/quickstart-minikube.md#deploy-wordpress

Kindly check. Can be reproduced. Do not have logs currently, will update if needed.

**Comment by jeremyrickard** [comment]
Hey @codevulture, I believe this is more of a Service Catalog issue? OSBA itself does not create the secrets (or anything) in Kubernetes. Can I suggest opening an issue in the Service Catalog repository with what you're looking for?

**Comment by jeremyrickard** [comment]
@codevulture I misunders

**Comment by codevulture** [comment]
@jeremyrickard : Sure, so everything was going good till the binding step(i.e when create binding is called), before binding is called we have secrets in k8s, i do not have env at the moment but 2 secrets are there originally(smtp pass/wordpress cred i think), at the binding step(i.e when binding resource is created), the secrets will contain the new creds and old secrets are overwritten. So in helm chart of wordpress env vars are referenced from secrets which includes old+new values from secrets and raises config error i think. ( To recreate i think steps could also be tried out manually using svcat or creating resources manually(i used helm get on installed wordpress and installed resources manually)) 

I will try to reproduce once i have env.

**Comment by krancour** [comment]
@codevulture, please correct me if I am misunderstanding, but I think what I am hearing is that you had _manually_ created a secret with the same name as the one that was written by Service Catalog during the binding?

What would be your reason for having done that?

**Comment by krancour** [comment]
Per the chart, the name of the secret written by Service Catalog during bind is `{{ template "fullname" . }}-mysql-secret`

https://github.com/Azure/helm-charts/blob/master/wordpress/templates/mysql-binding.yaml#L14

If you've followed the quickstart exactly, that is going to resolve to something like `osba-quickstart-osba-quickstart-mysql-secret`

There shouldn't be any reason for you to have created a secret with the same name as that.

Am I missing something?

**Comment by codevulture** [comment]
@krancour : by manually creating i mean running the https://github.com/Azure/helm-charts/blob/master/wordpress/templates/mysql-binding.yaml#L14 ( using kubectl create -f) , i mentioned `helm get` as the resource creation got failed 1st time due to config error but charts could be seen from using `helm get <wordpress chart>` from which we can see the actual chart with filled values.
I used the binding resource template from that to create the binding.

I did not created the secret manually i created the binding resource only. I faced this few weeks back so not sure but thought to create a reference if someone faces that. thanks.

**Comment by krancour** [comment]
@codevulture we're still not quite understanding you.

You've said this is reproducable. Please document the steps (actual commands) that reproduce.

Frankly, this looks like user error to me. `kubectl create -f` is not a command that should be involved in the installation of a helm chart, so it seems you've deviated from the steps documented in our quickstart.

**Comment by codevulture** [comment]
@krancour : Thanks for your response, maybe i missed something. Are the steps in quickstart working for you to deploy wordpress?  I am closing the bug and will reopen if i come across the issue with steps i followed.

**Comment by codevulture** [comment]
@krancour : thanks! Maybe I missed something.
