### ISSUE TITLE
CreateContainerConfigError wordpress and azure-mysql 

### ISSUE THREAD

**Issue by pas4gok** [Azure/open-service-broker-azure#410]
Followed the out of the box set up documentation for setting up Service Principal, Catalog, OSBA and Wordpress, all of them on the same RG. It worked until yesterday where the Azure MySql instance was automatically created as part of the wordpress installation and was able to successfully launch the wordpress app. 

Tried today on a different cluster (exactly the same version k8s 1.8.7) but only to end up in the following error on the logs 

_**container "osba-wordpress" in pod "osba-wordpress-d94fd86cb-prs44" is waiting to start: CreateContainerConfigError**_

Did something change on the OSBA or the helm chart recently ?.

**Comment by jeremyrickard** [comment]
Hey @pas4gok,

This can be a normal status. It could also be an error. That alone doesn’t really give us enough info to determine that here. If you could give us the output of describe as well, thst would be useful.

Here is what I mean by that: When provisioning and creating a binding, the binding will not be created until the instance is ready. The secret for the binding will not be created until the binding is ready. Finally, the pod has a reference to the secret in the spec. It will therefore fail with a similar error to that until the secret is created. 

It’s also possible there is an issue, but as I indicated above, there isn’t enough context to determine that right now.

**Comment by jeremyrickard** [comment]
@pas4gok wanted to follow up again and ask if you could give more info on your error? It would be useful if you could do a describe on the pod and paste that output here.

**Comment by krancour** [comment]
Closing this stale issue.
