### ISSUE TITLE
Add Application Insights Module

### ISSUE THREAD

**Issue by arschles** [Azure/open-service-broker-azure#42]

**Comment by kyschouv** [comment]
Any ETA on this? We'd like to use OSBA in a project, and this is the one thing missing.

**Comment by zhongyi-zhang** [comment]
Hi @kyschouv, we haven't scheduled for the module yet. Could you share the expectation of the module?

**Comment by kyschouv** [comment]
It would create an application insights resource (preferably with a specified resource name, so it could be easily found), and put the instrumentation key in a secret (through a binding perhaps? Similar to how Redis works).

**Comment by zhongyi-zhang** [comment]
Do we assume that the app is ready to enable App Insights, the only thing it required is the _instrumentation key_ to setup the client?

**Comment by zhongyi-zhang** [comment]
One more question, do you want to specify any more App Insights properties besides the kind (web, java, etc.)? Ref: https://docs.microsoft.com/en-us/rest/api/application-insights/components/createorupdate#request-body.

**Comment by kyschouv** [comment]
Yah we only ever need the instrumentation key (at least in our case). This is the ARM template we usually use when we're using app services (the `applicationId` probably isn't necessary):

```
    {
      "name": "[parameters('appInsightsName')]",
      "type": "Microsoft.Insights/components",
      "location": ["[variables('appInsightsLocation')]",](url)
      "apiVersion": "2014-04-01",
      "dependsOn": [],
      "properties": {
        "applicationId": "[variables('serviceId')]"
      }
    }
```

**Comment by zhongyi-zhang** [comment]
Cool. Thanks for the info. The requirement looks not complicated. We can add an experimental module for it. What is the acceptable ETA for you? Loose ETA is the end of next month for me. (Sorry I have a tight timeline recently.) If this is urgent for you, I am pleased making my time to deliver it in two weeks (if the code review also goes smooth).

**Comment by kyschouv** [comment]
It's not particularly urgent - end of next month would give us time to implement and test, as well as set up alerts against the resources. It'll be important to be able to specify the resource name for the app insights instances so we can find them and interact with them within the portal.

**Comment by zhongyi-zhang** [comment]
Nice. I'll be back to the thread when it is done.

**Comment by zhongyi-zhang** [comment]
@kyschouv the service is supported as an experimental module now. Have a try! Your feedback are welcome.
I am going to close the issue. Please create new issue if you have any enhancement request.
