### ISSUE TITLE
A long plan description causes a failure of creating service broker in CF

### ISSUE THREAD

**Issue by bingosummer** [Azure/open-service-broker-azure#427]
It seems the plan description is too long (more than 255 characters) in this [commit](https://github.com/Azure/open-service-broker-azure/commit/3a3441d6d89ca87641b113ef34d5c1fbe1bd7533), which causes a failure of creating service broker in CF.
```
$ cf create-service-broker xxx xxx xxx https://xxx
FAILED
Server error, status code: 500, error code: 10011, message: Database error
```

**Comment by jeremyrickard** [comment]
Hey @bingosummer, thanks for opening an issue with CF. I don't see any limitations in the OSB spec about length on this field. This feels very much like an issue with CF and not OSBA. I don't believe we hit this with Service Catalog.

**Comment by bingosummer** [comment]
@jeremyrickard , thanks for quick response.

The OSB spec only mentions that it should be a short description, but it doesn't mention how short it should be. openservicebrokerapi/servicebroker#509 is to ask OSB spec to add the limitations about length.

Agreed with you that it's as issue with CF cloud controller. cloudfoundry/cloud_controller_ng#1134 is to ask cloud_controller_ng to confirm that 255 is the limitation. If the limitation can't be fixed in a short term, OSBA may need to decrease the plan description length. Let's wait for their response.

**Comment by krancour** [comment]
iirc, during some discussion about this in the OSB group, there were some people not in favor of specifying a limit on length. I don't recall if that was the final word.

With no limit specified, this is definitely a CF issue, but I agree that we may be forced to adapt to this regardless.
