### ISSUE TITLE
"az redis create" command needs to be enhanced

### ISSUE THREAD

**Issue by dburkhalter-pivotal** [Azure/open-service-broker-azure#438]
# ensure 
az provider register --namespace Microsoft.Cache

# 
az redis create --name my-osba-cache --resource-group my-RG --location my-location --sku-name Basic  --sku-capacity 1 --sku-family C

**Comment by jeremyrickard** [comment]
@dburkhalter-pivotal thanks for the issue. If I can clarify a moment, your subscription didn't have the Microsoft.Cache provider registered and you needed to run the `az provider register` command?

**Comment by dburkhalter-pivotal** [comment]
Will come back with more details, but as mentioned az command sounds have
changed

But you are right one must register the cache provider

Envoyé de mon iPhone

Le 22 mai 2018 à 16:22, Jeremy Rickard <notifications@github.com> a écrit :

@dburkhalter-pivotal <https://github.com/dburkhalter-pivotal> thanks for
the issue. If I can clarify a moment, your subscription didn't have the
Microsoft.Cache provider registered and you needed to run the az provider
register command?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/open-service-broker-azure/issues/438#issuecomment-391008893>,
or mute the thread
