### ISSUE TITLE
Update test in lifecycle

### ISSUE THREAD

**Issue by zhongyi-zhang** [Azure/open-service-broker-azure#465]
Some of the update APIs have been implemented. But the lifecycle test doesn't cover it.
I'd love to help on this if you are focusing on something else.

**Comment by jeremyrickard** [comment]
Go for it!

**Comment by zhongyi-zhang** [comment]
@jeremyrickard @krancour I am now working on it and almost done.
I covered updating service plans and the lifecycle test could pass. But when I tested it in CF, it failed to update service plan. Then, I found https://github.com/Azure/open-service-broker-azure/issues/497. Will OSBA allow to update service plan? If yes, I think the PR could just cover updating service plans. It doesn't matter test check-in is earlier, right?

**Comment by zhongyi-zhang** [comment]
The update test is going to remove service plan updating, as the discussion in https://github.com/Azure/open-service-broker-azure/issues/497 decided not to support changing plan for now.
