### ISSUE TITLE
Make stability attribute of services/plans instead of module

### ISSUE THREAD

**Issue by krancour** [Azure/open-service-broker-azure#466]
Module is an internal construct and simply a consequence of how we organize code. It doesn't mean anything from an OSB perspective.

We've agreed that we have some modules where some of the services and plans vary from one another in terms of stability, so we want to move the stability level attribute "down" to the service & plan level so that when filtering what is included in the catalogs on stability, the decision to include or not include something is made at a lower level than it is now.

**Comment by jeremyrickard** [comment]
Closed by #471
