### ISSUE TITLE
JSON Schema: location property should be required if no default

### ISSUE THREAD

**Issue by prydonius** [Azure/open-service-broker-azure#469]
The broker doesn't specify that the "location" property is required, but if it is omitted the ServiceInstance gets into an error state:

```
Error provisioning ServiceInstance of ClusterServiceClass (K8S: "997b8372-8dac-40ac-ae65-758b4a5075a5" ExternalName: "azure-mysql-5-7") at ClusterServiceBroker "osba": Status: 400; ErrorMessage: ValidationError; Description: The value provided for location is invalid: invalid location: ""; ResponseError: <nil>
```

See slack conversation: https://kubernetes.slack.com/archives/C9D3TSUG4/p1528155057000173

**Comment by krancour** [comment]
There has recently been major changes to how we handle the location parameter. This _should_ be fixed in master already as a result of those changes. If it turns out I am wrong, please re-open.
