### ISSUE TITLE
Duplicate fields in some json schema

### ISSUE THREAD

**Issue by jeremyrickard** [Azure/open-service-broker-azure#491]
There is some duplication in some of the JSON schema required fields entries. This is invalid JSON schema and prevents the broker from working with CF.

**Comment by krancour** [comment]
Adding a little color and context to this issue-- the fundamental problem is that services and plans are mutable (can be modified after instantiation) even though that is not a behavior we had really intended. There is at least one place where we unintentionally made the same modification to a plan twice-- both times, we add `alias` (or `parentAlias`, as the case may be) to the list of required provisioning parameters. This really shouldn't happen at all!

@jeremyrickard has opened #492 to make services and plans truly immutable. What we then do is ad-hoc instantiate _new_ plans augmented with these additional details when needed and this avoids the scenario where we accidentally made the same modification to a plan twice (when we shouldn't have modified them at all).
