### ISSUE TITLE
Developer Documentation for using broker-cli is out of date

### ISSUE THREAD

**Issue by ageekymonk** [Azure/open-service-broker-azure#493]
Hi, 

  The documentation for how to locally develop  and interact with the broker using **broker-cli** is out of date.

**Comment by krancour** [comment]
That seems as if it's probably true. Can @ageekymonk, can you please help us out a bit by pinpointing where in the documentation things started not working for you?

**Comment by krancour** [comment]
Believe this was fixed by #506. Please re-open if I've got that wrong.
