### ISSUE TITLE
RFE - test/document usage with MAG

### ISSUE THREAD

**Issue by jduncan-rva** [Azure/open-service-broker-azure#495]
Test and document any changes needed for the service broker to function properly in MAG.

**Comment by krancour** [comment]
MAG?

**Comment by jduncan-rva** [comment]
Microsoft Azure for Government. Sorry. Didn't know the acronym wasn't common. Different API endpoints, etc.

**Comment by krancour** [comment]
It's actually not supported at all, yet...

This may be a duplicate of #250. I think #250 was probably requested for the sake of the China cloud, but the effort that would probably take care of US gov cloud as well.

**Comment by krancour** [comment]
I'm going to close this only because it does seem to be a dup of #250.
