### ISSUE TITLE
DOC - some provisioning parameters description doesn't correctly reflect the catalog

### ISSUE THREAD

**Issue by zhongyi-zhang** [Azure/open-service-broker-azure#496]
For example, https://github.com/Azure/open-service-broker-azure/blob/master/docs/modules/mysql.md#provisioning-parameters<br />
Valid values for `cores` in `general-purpose` plan should be `{2, 4, 8, 16, 32}`. And the default value should be `2`. Similar issue in `memory-optimized` plan.<br />

Is it time to implement auto generating plan schemas of the docs? <br />
As plan properties and schemas in catalog have well driven all the details, manual synchronous updating docs is a duplicated job. And there are so many plans. Even semi-auto generation is much better.

**Comment by jeremyrickard** [comment]
@zhongyi-zhang I think the answer is we *should* look at auto-generating plan schema docs now that we are defining those things in a reliable place. I'm not sure we have the bandwidth to tackle that right now. I think it would be a fantastic thing to do long term though.

I've gone ahead and updated the doc for this one.
