### ISSUE TITLE
MSSQL should be able to update plan from basic to standard

### ISSUE THREAD

**Issue by zhongyi-zhang** [Azure/open-service-broker-azure#497]
https://github.com/Azure/open-service-broker-azure/blob/master/pkg/service/catalog.go#L33
As `PlanUpdatable` is default to `false`, users can't update MSSQL instances from basic plan to standard/premium plan. Also, changing tier from DTU model to vCore model is doable. Similar to MySQL and PostgreSQL.

**Comment by jeremyrickard** [comment]
Hey @zhongyi-zhang, @krancour and I had discussed this and we didn't want to allow the plans to change. I know that it's possible to do that with MS SQL via the portal, but we wanted to keep the broker simpler for now. We don't have good roll-back capabilities for now, and PostgreSQL and MySQL do *not* support that so we thought we'd keep things as simple as possible for now and just allow update to the instance in terms of params, not plans.

**Comment by krancour** [comment]
Also, fwiw, vCore stuff for MS SQL is still in preview. I wouldn't want to implement update from a stable plan (the DTU-based ones) to a plan of lesser stability.

**Comment by zhongyi-zhang** [comment]
It makes sense to me. Closed the issue. When it is proved to be a strong requirement, we can open another issue for it.
