### ISSUE TITLE
Authorization error when deploying helm chart

### ISSUE THREAD

**Issue by alexjh** [Azure/open-service-broker-azure#504]
```bash
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-04-26T23:34:53Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}


$ helm install azure/open-service-broker-azure --name osba --namespace osba --set azure.subscriptionId=${AZURE_SUBSCRIPTION_ID} --set azure.tenantId=${AZURE_TENANT_ID} --set azure.clientId=${AZURE_CLIENT_ID} --set azure.clientSecret=${AZURE_CLIENT_SECRET} --set azure.defaultLocation=${LOCATION} --set redis.persistence.storageClass=persistent --version 1.0.1
Error: release osba failed: .authorization.k8s.io "" is invalid: spec.user: Invalid value: "": at least one of user or group must be specified
$ helm list | grep osba
osba    1               Tue Jun 26 15:59:44 2018        FAILED          open-service-broker-azure-1.0.1 osba     
```

The broker itself seems to be working fine, I can set up a service through Cloud Foundry and the apps can use them.

I'm happy to get more information, but I don't know where to look. I've grepped through the helm chart and don't see any references to  `.authorization.k8s.io`, so I'm really confused about where this error is coming from.

**Comment by asos-williamayerst** [comment]
authorization.k8s.io is the kubernetes response - the thing you should be looking for is the 'user' field in one of the various resource yamls...

**Comment by jeremyrickard** [comment]
Hey @alexjh, will look into this for you today. Can you provide a little additional info?

What sort of cluster are you running: [GKE, EKS, AKS, Minikube, Other]
Did your Service Catalog installation finish correctly:
Which version of K8s:

**Comment by alexjh** [comment]
Hi! Thanks for looking into this. It's a Vagrant box with our own SUSE RPMs, so `Other`, but I would say it's Minikube like.

I believe it installed correctly, but I don't know how to confirm. I see the pods running:
 
```bash
$ kubectl -n catalog get pods -a
NAME                                                  READY     STATUS    RESTARTS   AGE
catalog-catalog-apiserver-77549fbdbd-htw2b            2/2       Running   0          3d
catalog-catalog-controller-manager-857dc576cf-7r5ch   1/1       Running   1          3d
```

K8s version: 1.9.6.

**Comment by dewnull** [comment]
I am getting the same error and I am using Azure AKS.

**Comment by jeremyrickard** [comment]
@alexjh @dewnull any chance you could share any more error information that you are receiving? 

@dewnull, could you also share your helm install command, if it differs from:

```console
helm install azure/open-service-broker-azure --name osba --namespace osba \
  --set azure.subscriptionId=$AZURE_SUBSCRIPTION_ID \
  --set azure.tenantId=$AZURE_TENANT_ID \
  --set azure.clientId=$AZURE_CLIENT_ID \
  --set azure.clientSecret=$AZURE_CLIENT_SECRET
```

**Comment by dewnull** [comment]
@jeremyrickard after deleting and reinstalling Service Catalog and osba, it seems to work okay.  
Initially I had installed Service Catalog using:

```console
helm install svc-cat/catalog --name catalog --namespace catalog --set rbacEnable=false --set apiserver.auth.enabled=false --set controllerManager.healthcheck.enabled=false
```
I used helm to `delete --purge` and reinstalled Service Catalog using:
```console
 helm install svc-cat/catalog --name catalog --namespace catalog --set rbacEnable=false
``` 
and installed OSBA using: 

```console
helm install azure/open-service-broker-azure --name osba --namespace osba \
  --set azure.subscriptionId=$AZURE_SUBSCRIPTION_ID \
  --set azure.tenantId=$AZURE_TENANT_ID \
  --set azure.clientId=$AZURE_CLIENT_ID \
  --set azure.clientSecret=$AZURE_CLIENT_SECRET
```

**Comment by kriszentner** [comment]
@dewnull Thanks for the fix. The documentation that lead me to the first command is here (and should perhaps be corrected?):
https://docs.microsoft.com/en-us/azure/aks/integrate-azure

Using your svc-cat/catalog command without the `--set apiserver.auth.enabled=false --set controllerManager.healthcheck.enabled=false` also rid me of this error.

**Comment by alexjh** [comment]
Thanks for looking into this! I was on vacation so I wasn't able to answer your questions, but it looks like it's been resolved!

**Comment by badalk** [comment]
I am facing the same issue on AKS. My cluster is RBAC enabled. Do I still need to install service catalog with rbacEnable set to false to get over this issue? Sometimes I am also getting error as 

`Error: release osba failed: the server is currently unable to handle the request (post clusterservicebrokers.servicecatalog.k8s.io)`
