### ISSUE TITLE
Error message in binding isn't wrote to http response

### ISSUE THREAD

**Issue by zhongyi-zhang** [Azure/open-service-broker-azure#523]
In api/bind, [func `handleBindingError`](https://github.com/Azure/open-service-broker-azure/blob/master/pkg/api/bind.go#L325) handles errors. It writes error message to the broker store and the log, but doesn't write to response. So users can't directly see the message. Same in api/unbind.

**Comment by krancour** [comment]
This is deliberate. iirc, any error that is the user's fault (e.g. malformed request, parameter validation failed, etc.), the cause _is_ included in the response. However, the only errors that are handled by `handleBindingError` (again, iirc) are _500 internal server errors_. Generally, it is not considered a good practice to share details of an internal error with users.

**Comment by zhongyi-zhang** [comment]
It makes sense.
