### ISSUE TITLE
Experimental version deployment on ACS-Engine based K8S deployment

### ISSUE THREAD

**Issue by ipolyzos** [Azure/open-service-broker-azure#525]
Hello, 

 I have tried to deploy the _"experimental"_ version _(branch roadmap-update-june2018)_ of [OSBA]( https://github.com/Azure/open-service-broker-azure) on [acs-engine](https://github.com/Azure/acs-engine) based K8S deployment. Even though the deployment succeeds and I can access stable services I don't have access to the experimental components such as "Azure KeyVault".

 The script used along with the references to the documentation can be found at [github.com/ipolyzos/acs-engine-kubernetes-osba-installer](https://github.com/ipolyzos/acs-engine-kubernetes-osba-installer).

 Could you please advice ?

Regards, 
IP

**Comment by jeremyrickard** [comment]
Hey @ipolyzos, when we cut the 1.0.x release of OSAB, we ended up disabling all the "experimental" services. We plan on adding MOST (ACI is being removed) of them back in 1.1.0, which should be released in a short time. In the meantime, if you use the v0.11.0 version of the Helm chart, you'll get all the external services back! 

Sorry for the inconvenience, we're working to re-enable those module ASAP.

**Comment by ipolyzos** [comment]
Thanks a lot @jeremyrickard , I'm looking forward to the 1.1.0 release.
