### ISSUE TITLE
Assert compliance with OSB spec

### ISSUE THREAD

**Issue by krancour** [Azure/open-service-broker-azure#54]
@Haishi2016 has written a nice suite for doing this. It should be integrated into our own test suite.

https://github.com/Haishi2016/osb-checker

Since I expect that many (slight) deviations exist, this additional assertion should not, initially, fail the CI pipeline if issues are found.

We can address each finding individually (as its own issue) before requiring this assertion to pass.

**Comment by jeremyrickard** [comment]
Closed with #85 and #108 
API compliance issues will be handled with separate issues.
