### ISSUE TITLE
Question: How do you find AZURE_TENANT_ID, AZURE_CLIENT_ID and AZURE_CLIENT_SECRET

### ISSUE THREAD

**Issue by alberttwong** [Azure/open-service-broker-azure#540]
Using OpenShift.   Trying to find    

-p AZURE_TENANT_ID=$AZURE_TENANT_ID \
   -p AZURE_CLIENT_ID=$AZURE_CLIENT_ID \
   -p AZURE_CLIENT_SECRET=$AZURE_CLIENT_SECRET \

.   When I searched the docs, they said to navigate to Active Directory (works) and then "Click the application that you are working on and then click Configure" (my workspace is blank). 

Does the "Directory ID" also mean AZURE_TENANT_ID?   Do I follow the steps at https://www.netiq.com/communities/cool-solutions/creating-application-client-id-client-secret-microsoft-azure-new-portal/ to create a "app registration" and follow the rest of the doc to get the rest of the settings?

**Comment by jeremyrickard** [comment]
Hey @alberttwong sorry for the delayed response. Directory ID == Tenant ID.


If you're encountering issues still, more generally these come from creating a service principal. There are few ways to do create them, which you can find in [documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal).

A quick way to get these would be using the CLI:

```
az ad sp create-for-rbac --name osba -o table
```

The output of this should be a tabular block with a few pieces of data:

```
AppId                                 DisplayName        Name                      Password                              Tenant
------------------------------------  -----------------  ------------------------  ------------------------------------  ------------------------------------
<AZURE_CLIENT_ID>  osba  http://osba-quickstart22  <AZURE_CLIENT_SECRET>  <TENANT_ID>
```
