### ISSUE TITLE
Azure components in OpenShift.  I only get some of the Azure components.

### ISSUE THREAD

**Issue by alberttwong** [Azure/open-service-broker-azure#542]
I only see Azure databases.   However in the screenshot at https://azure.microsoft.com/en-us/blog/openshift-on-azure-the-easiest-fully-managed-openshift-in-the-cloud/, there are many more azure components.    Am I missing something?

![screen shot 2018-08-08 at 11 46 35 am](https://user-images.githubusercontent.com/749093/43857631-c9038d8e-9b00-11e8-8aab-597a47101179.png)

**Comment by krancour** [comment]
The screenshot seems to include experimental modules. Those are disabled by default. There is an install-time option for enabling them-- but be warned that "experimental" means those services are still under development and subject to breaking changes even in minor releases.
