### ISSUE TITLE
Stablility related statements in docs need to be updated

### ISSUE THREAD

**Issue by zhongyi-zhang** [Azure/open-service-broker-azure#548]
As stability is a plan level property now, but the docs still describe it as a module property. And some of the service modules are stable now. But it is still PREVIEW in the module doc e.g. https://github.com/Azure/open-service-broker-azure/blob/master/docs/modules/mssql.md.

Plus, either of MSSQL, PostgreSQL, and MySQL, the service names don't contain server version against that the names in catalog actually contain server version.

**Comment by jeremyrickard** [comment]
@zhongyi-zhang thanks for the issue! I'll get a docs PR out today.
