### ISSUE TITLE
Why judge empty in update?

### ISSUE THREAD

**Issue by norshtein** [Azure/open-service-broker-azure#550]
Hi, it is noticed in [pkg/api/update.go#L367](https://github.com/Azure/open-service-broker-azure/blob/master/pkg/api/update.go#L367), the code judges whether the value is empty. The value is raw content provided by user, and the user might update the instance using empty value. For example, user might [update a cosmos instance](https://github.com/Azure/open-service-broker-azure/pull/544) using `{"readRegions": []}` to delete all existing read regions. Is there any special concern doing the judgement here?

**Comment by krancour** [comment]
@norshtein have a look at the comment above that line. It explains why it is done. Short answer is that it is to conform to spec.

**Comment by krancour** [comment]
But... I'll review whether there is a better way to do this that will conform with spec _and_ address your use case.

**Comment by krancour** [comment]
Ok... ya... there's no point to that line.

I agree it should go.
