### ISSUE TITLE
Implement a "Bring Your Own" capability to register an existing SQL Server instance

### ISSUE THREAD

**Issue by jeremyrickard** [Azure/open-service-broker-azure#559]
We should implement a new "byob" style service for SQL Server that will enable customers to bring an existing SQL Server instance into the OSBA fold.

OSBA should be able to:
* Create bindings on this instance
* Remove bindings from this instance

Out of scope:
* Deprovision
* creating new databases on the SQL Server

**Comment by norshtein** [comment]
Hey, I think @zhongyi-zhang has implemented this feature.

**Comment by jeremyrickard** [comment]
@zhongyi-zhang can you open a PR for this if you've already started? would be cool to start looking at it and figure out anything that needs to change in the broker.

**Comment by zhongyi-zhang** [comment]
@jeremyrickard it is done but hard to create a pure PR. Let me explain. Several months ago, in the discussion with Aaron, he thought some CF scenarios are out of OSBA scope. So, we temporarily decided to develop an "advanced OSBA" for CF users only. We planed to regularly merge upstream OSBA codes, and develop no-conflict features carefully. As a result, we have this repo: https://github.com/CloudFoundryOnAzure/open-service-broker-azure. It is still under development and doesn't have any release. Registering an existing SQL server as a service instance is a part of this PR: https://github.com/CloudFoundryOnAzure/open-service-broker-azure/pull/3. It bases on some other changes.
I saw the mail thread about the meeting with you and Ning. Glad to hear that we will keep one branch. I think we can discuss how to deal with it later after you understand the overview of CF advanced requirements and what we tried to implement. We are sorting the related docs and will share them soon. Any of your thoughts are super appreciated.  I really love your thoughts and works on OSBA.

**Comment by krancour** [comment]
I used to like this idea, however, my thoughts are changing a bit.

If the driver for this is to facilitate migrations from MASB to OSBA, there's a simpler plan that's now been proposed. I think that plan needs further consideration and discussion before committing to the BYO feature.

**Comment by norshtein** [comment]
Hi @krancour , if you are worried about "byob" service may affect normal users usage, @zhongyi-zhang has set up a mechanism that "byob" service is default off and invisible to users, it becomes visible after the user turning it on in the manifest. 

I think "byob" service is necessary since many customers are managing Azure SQL server by themselves and they want to take advantage of OSBA to make their access safer and more convenient.

**Comment by zhongyi-zhang** [comment]
Closed via #570.
