### ISSUE TITLE
Error provisioning azure-mysql-5-7 basic plan

### ISSUE THREAD

**Issue by arapulido** [Azure/open-service-broker-azure#563]
Hello,

I am running Service Catalog 0.1.31 and OSBA 1.1.0 on minikube. I had never had issues with provisioning a mysql instance everytime I tried. Today I created a new minikube cluster and tried those versions and the provisioning failed.

Logs don't show anything useful. Automatically, because of the failure of the provisioning, the auto-deprovision kicks off and the osba pods crashes:

```
panic: interface conversion: service.InstanceDetails is nil, not *mysql.allInOneInstanceDetails

goroutine 137 [running]:
github.com/Azure/open-service-broker-azure/pkg/services/mysql.(*allInOneManager).deleteARMDeployment(0xc4200800b0, 0xc348c0, 0xc420063dc0, 0xc420028900, 0x24, 0x0, 0x0, 0xc420028930, 0x24, 0xc3a380, ...)
	/go/src/github.com/Azure/open-service-broker-azure/pkg/services/mysql/all_in_one_deprovision.go:23 +0x178
github.com/Azure/open-service-broker-azure/pkg/services/mysql.(*allInOneManager).(github.com/Azure/open-service-broker-azure/pkg/services/mysql.deleteARMDeployment)-fm(0xc348c0, 0xc420063dc0, 0xc420028900, 0x24, 0x0, 0x0, 0xc420028930, 0x24, 0xc3a380, 0xc420362480, ...)
	/go/src/github.com/Azure/open-service-broker-azure/pkg/services/mysql/all_in_one_deprovision.go:14 +0x79
github.com/Azure/open-service-broker-azure/pkg/service.(*deprovisioningStep).Execute(0xc4201018e0, 0xc348c0, 0xc420063dc0, 0xc420028900, 0x24, 0x0, 0x0, 0xc420028930, 0x24, 0xc3a380, ...)
	/go/src/github.com/Azure/open-service-broker-azure/pkg/service/deprovisioner.go:67 +0xe5
github.com/Azure/open-service-broker-azure/pkg/broker.(*broker).executeDeprovisioningStep(0xc42008e100, 0xc348c0, 0xc420063d00, 0xc37ee0, 0xc420063cc0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/Azure/open-service-broker-azure/pkg/broker/deprovision.go:91 +0x619
github.com/Azure/open-service-broker-azure/pkg/broker.(*broker).(github.com/Azure/open-service-broker-azure/pkg/broker.executeDeprovisioningStep)-fm(0xc348c0, 0xc420062540, 0xc37ee0, 0xc420063cc0, 0xc420078718, 0x1, 0xc37ee0, 0xc420063cc0, 0x0)
	/go/src/github.com/Azure/open-service-broker-azure/pkg/broker/broker.go:77 +0x56
github.com/Azure/open-service-broker-azure/pkg/async/redis.(*engine).defaultExecuteTasks(0xc420079930, 0xc348c0, 0xc420062540, 0xc4200d84e0, 0xba0086, 0xc, 0xba0855, 0xd, 0xc4200d85a0)
	/go/src/github.com/Azure/open-service-broker-azure/pkg/async/redis/tasks_executor.go:90 +0x361
github.com/Azure/open-service-broker-azure/pkg/async/redis.(*engine).(github.com/Azure/open-service-broker-azure/pkg/async/redis.defaultExecuteTasks)-fm(0xc348c0, 0xc4200620c0, 0xc4200d84e0, 0xba0086, 0xc, 0xba0855, 0xd, 0xc4200d85a0)
	/go/src/github.com/Azure/open-service-broker-azure/pkg/async/redis/engine.go:70 +0x83
created by github.com/Azure/open-service-broker-azure/pkg/async/redis.(*engine).Run.func3
	/go/src/github.com/Azure/open-service-broker-azure/pkg/async/redis/engine.go:172 +0x1a8
```

**Comment by norshtein** [comment]
Hi @arapulido , could you provide the command you use to create the instance? And, if possible, the log of provisioning. 
And I think the error in deprovision is explainable: an error happened in very early provisioning , causing the service instance detail is `nil`, which caused later type assertion failed. A fix will be added later. Thanks for bringing up the issue.

**Comment by jamesread** [comment]
I just got this from a fresh deploy on OpenShift 3.10. The Redis pod looks like it's running OK.

I'm not sure how to get the original provisioning command, but if you can tell me I'll dig it up for you.

```
time="2018-09-10T19:13:10Z" level=info msg="Open Service Broker for Azure starting" commit=7b46be0 version=v1.0.1
time="2018-09-10T19:13:10Z" level=info msg="Setting log level" logLevel=INFO
time="2018-09-10T19:13:10Z" level=info msg="Sensitive instance and binding details will be encrypted" encryptionScheme=AES256
time="2018-09-10T19:13:10Z" level=info msg="API server is listening" address="http://0.0.0.0:8080 "
panic: interface conversion: service.InstanceDetails is nil, not *mysql.allInOneInstanceDetails

goroutine 51 [running]:
github.com/Azure/open-service-broker-azure/pkg/services/mysql.(*allInOneManager).deleteARMDeployment(0xc42007e0a0, 0xacba40, 0xc4204f2a00, 0xc420078420, 0x24, 0x0, 0x0, 0xc420078450, 0x24, 0xacffe0, ...)
	/go/src/github.com/Azure/open-service-broker-azure/pkg/services/mysql/all_in_one_deprovision.go:23 +0x178
github.com/Azure/open-service-broker-azure/pkg/services/mysql.(*allInOneManager).(github.com/Azure/open-service-broker-azure/pkg/services/mysql.deleteARMDeployment)-fm(0xacba40, 0xc4204f2a00, 0xc420078420, 0x24, 0x0, 0x0, 0xc420078450, 0x24, 0xacffe0, 0xc42034fb00, ...)
	/go/src/github.com/Azure/open-service-broker-azure/pkg/services/mysql/all_in_one_deprovision.go:14 +0x79
github.com/Azure/open-service-broker-azure/pkg/service.(*deprovisioningStep).Execute(0xc420101540, 0xacba40, 0xc4204f2a00, 0xc420078420, 0x24, 0x0, 0x0, 0xc420078450, 0x24, 0xacffe0, ...)
	/go/src/github.com/Azure/open-service-broker-azure/pkg/service/deprovisioner.go:67 +0xe5
github.com/Azure/open-service-broker-azure/pkg/broker.(*broker).executeDeprovisioningStep(0xc42008cf00, 0xacba40, 0xc4204f2800, 0xacdfc0, 0xc4204f27c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/Azure/open-service-broker-azure/pkg/broker/deprovision.go:91 +0x619
github.com/Azure/open-service-broker-azure/pkg/broker.(*broker).(github.com/Azure/open-service-broker-azure/pkg/broker.executeDeprovisioningStep)-fm(0xacba40, 0xc42008c6c0, 0xacdfc0, 0xc4204f27c0, 0xc420077758, 0x1, 0xacdfc0, 0xc4204f27c0, 0x0)
	/go/src/github.com/Azure/open-service-broker-azure/pkg/broker/broker.go:77 +0x56
github.com/Azure/open-service-broker-azure/pkg/async/redis.(*engine).defaultExecuteTasks(0xc4200775f0, 0xacba40, 0xc42008c6c0, 0xc4203c0300, 0xa4f477, 0xc, 0xa4fb47, 0xd, 0xc4203c03c0)
	/go/src/github.com/Azure/open-service-broker-azure/pkg/async/redis/tasks_executor.go:90 +0x361
github.com/Azure/open-service-broker-azure/pkg/async/redis.(*engine).(github.com/Azure/open-service-broker-azure/pkg/async/redis.defaultExecuteTasks)-fm(0xacba40, 0xc42008c000, 0xc4203c0300, 0xa4f477, 0xc, 0xa4fb47, 0xd, 0xc4203c03c0)
	/go/src/github.com/Azure/open-service-broker-azure/pkg/async/redis/engine.go:70 +0x83
created by github.com/Azure/open-service-broker-azure/pkg/async/redis.(*engine).Run.func3
	/go/src/github.com/Azure/open-service-broker-azure/pkg/async/redis/engine.go:172 +0x1a8

```

**Comment by arapulido** [comment]
Hello, this is the command I used to to provision the instance:
```svcat provision my-instance --class azure-mysql-5-7 --plan basic -p location=eastus -p resourceGroup=my-rg -v99 ```

The weird thing is I didn't get any logs from provisioning, only from the failed deprovisioning

**Comment by norshtein** [comment]
Hi @arapulido , I agree it's very weird... Are you able to reproduce this error? Does this error happen every time you create the service instance or it appears occasionally?

**Comment by arapulido** [comment]
OK, I think I know what's seems to be going on. It seems that the service principal I was using was no longer in my subscription (maybe I deleted it and forgot about it, or someone else deleted it). Creating a new SP worked for me.

But two questions:

 * The OSBA catalog was being retrieved correctly even when I was using the un-existing SP. Retrieving the catalog doesn't require any authentication?
* If the problem was wrong auth when provisioning (SP non existing), shouldn't I get proper errors in the logs?

Thanks!

**Comment by krancour** [comment]
@arapulido 

> The OSBA catalog was being retrieved correctly even when I was using the un-existing SP. Retrieving the catalog doesn't require any authentication?

Catalog retrieval doesn't involve any calls out to Azure. The catalog is contained directly within OSBA.

**Comment by zhongyi-zhang** [comment]
>If the problem was wrong auth when provisioning (SP non existing), shouldn't I get proper errors in the logs?

@krancour I think an improvement to this problem is valuable. We can return more useful info in polling to show the current status of the instance. At least, the broker lets users see the error message when something goes wrong.
We can expose the error message here: https://github.com/Azure/open-service-broker-azure/blob/master/pkg/api/poll.go#L91
Also in line 117 & 144.

**Comment by norshtein** [comment]
Hi @arapulido , I tried to repro your case but failed. I created a service principal and used it to provision something firstly, and then deleted SP, and then tried to provision the same resource as you provisioned, but I did get the error message from provisioning:

>    2018-09-12T04:55:05.26+0000 [APP/PROC/WEB/0] ERR time="2018-09-12T04:55:05Z" level=error msg="error executing job; not submitting any follow-up tasks" error="error executing provisioning step \"preProvision\" for instance \"92e88ee6-fe45-4abd-83bc-85e235ae2ef9\": error executing provisioning step: error determining server name availability: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/c4528d9e-c99a-48bb-b12d-fde2176a43b8/providers/Microsoft.DBforMySQL/checkNameAvailability?api-version=2017-04-30-preview: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"unauthorized_client\",\"error_description\":\"AADSTS70001: Application with identifier '73dd71f4-3828-4193-8909-41c5fe1cc748' was not found in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47\\r\\nTrace ID: dcd05923-f206-4478-bc77-798f11c61300\\r\\nCorrelation ID: 3bcfbd4e-e723-4dbc-9600-41d4524b23df\\r\\nTimestamp: 2018-09-12 04:55:14Z\",\"error_codes\":[70001],\"timestamp\":\"2018-09-12 04:55:14Z\",\"trace_id\":\"dcd05923-f206-4478-bc77-798f11c61300\",\"correlation_id\":\"3bcfbd4e-e723-4dbc-9600-41d4524b23df\"}" job=executeProvisioningStep taskID=b23ee68f-ded3-49f1-842a-804f252c4ae8

That's reasonable and the error is gotten from [here](https://github.com/Azure/open-service-broker-azure/blob/master/pkg/services/mysql/all_in_one_provision.go#L28). I think you might have encountered an occasional error.

**Comment by arapulido** [comment]
Weird. Thanks @norshtein et al. for the help. I will close this issue now, and will re-open if eventually I reproduce it again. Thanks!
