### ISSUE TITLE
Service Binding Credentials for azure-storage missing endpoint information

### ISSUE THREAD

**Issue by shawn-nielsen** [Azure/open-service-broker-azure#578]
The azure-storage service with the general-purpose-storage-account plan is missing the endpoint to the storage in the binding credentials.

Currently the binding credentials show:
accessKey
storageAccountName

**Comment by shawn-nielsen** [comment]
The 'PRIMARY BLOB SERVICE ENDPOINT' would be ideal

**Comment by norshtein** [comment]
Hi @shawn-nielsen ,sorry for late response and thanks for raising this issue. What do you mean by "PRIMARY BLOB SERVICE ENDPOINT"? Is that something like this: `DefaultEndpointsProtocol=https;AccountName=myaccountname;AccountKey=Mz6/Ju27lXQrbtHEfFUIARoxcrEcF88awJ+/os8lpOfDjdmz8o5YlAueMg7Koi1u1JIU9O5rXQLTwJFzFxy1iA==;EndpointSuffix=core.windows.net`? If so, we can add it to current credentials.

**Comment by norshtein** [comment]
Fixed via #608 . Feel free to reopen it if you have any question.
