### ISSUE TITLE
Can't provision new database on existing RDBMS

### ISSUE THREAD

**Issue by timwebster9** [Azure/open-service-broker-azure#583]
I've created an Azure PostgreSQL database server using azure CLI.  I am then trying to provision new database instances using the `azure-postgresql-9-6-database` class, and failing.  The service instance gets stuck in 'provisioning' status, and never appears on the RDBMS.  Also, when I try to then delete the instance, it never goes away.

I can provision them both at the same time using `azure-postgresql-9-6` easily.

So 2 things:

- how can I troubleshoot the provisioning problem?  I don't see anything strange in the catalog logs (and nothing shows up at all in the OSBA pod logs).  `svcat describe instance` returns nothing interesting either, just `Provisioning - The instance is being provisioned asynchronously @ 2018-09-24 19:20:02 +0000 UTC`, even after it's marked for deletion.
- how can I delete the stuck instance?  Both `kubectl delete serviceinstance` and `svcat deprovision` can't seem to get rid of it.

**Comment by timwebster9** [comment]
I re-installed OSBA with `logLevel=DEBUG` and I'm seeing this:

```
time="2018-09-24T21:27:01Z" level=info msg="Open Service Broker for Azure starting" commit=ab0b831 version=v1.1.0
time="2018-09-24T21:27:01Z" level=info msg="Setting log level" logLevel=DEBUG
time="2018-09-24T21:27:01Z" level=info msg="Sensitive instance and binding details will be encrypted" encryptionScheme=AES256
time="2018-09-24T21:27:01Z" level=info msg="API server is listening with TLS enabled" address="https://0.0.0.0:8443"
time="2018-09-24T21:28:45Z" level=debug msg="received provisioning request" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:28:45Z" level=debug msg="parent not provisioned, waiting" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:28:45Z" level=debug msg="asynchronous provisioning initiated" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:28:46Z" level=debug msg="received polling request" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:28:46Z" level=debug msg="provisioning is deferred" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d operation=provisioning status=PROVISIONING_DEFERRED
time="2018-09-24T21:28:49Z" level=debug msg="received polling request" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:28:49Z" level=debug msg="provisioning is deferred" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d operation=provisioning status=PROVISIONING_DEFERRED
time="2018-09-24T21:28:53Z" level=debug msg="received polling request" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:28:53Z" level=debug msg="provisioning is deferred" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d operation=provisioning status=PROVISIONING_DEFERRED
time="2018-09-24T21:29:01Z" level=debug msg="received polling request" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:29:01Z" level=debug msg="provisioning is deferred" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d operation=provisioning status=PROVISIONING_DEFERRED
time="2018-09-24T21:29:17Z" level=debug msg="received polling request" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:29:17Z" level=debug msg="provisioning is deferred" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d operation=provisioning status=PROVISIONING_DEFERRED
time="2018-09-24T21:29:45Z" level=debug msg="parent not done, will wait again" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:29:49Z" level=debug msg="received polling request" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:29:49Z" level=debug msg="provisioning is deferred" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d operation=provisioning status=PROVISIONING_DEFERRED
time="2018-09-24T21:30:45Z" level=debug msg="parent not done, will wait again" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:30:53Z" level=debug msg="received polling request" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:30:53Z" level=debug msg="provisioning is deferred" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d operation=provisioning status=PROVISIONING_DEFERRED
time="2018-09-24T21:31:45Z" level=debug msg="parent not done, will wait again" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:32:45Z" level=debug msg="parent not done, will wait again" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:33:01Z" level=debug msg="received polling request" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:33:01Z" level=debug msg="provisioning is deferred" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d operation=provisioning status=PROVISIONING_DEFERRED
time="2018-09-24T21:33:45Z" level=debug msg="parent not done, will wait again" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
time="2018-09-24T21:34:45Z" level=debug msg="parent not done, will wait again" instanceID=b68f4f93-c040-11e8-895c-96dbda7b108d
```

**Comment by norshtein** [comment]
I guess you have used incorrect provisioning parameters. When you created `azure-postgresql-9-6-database`, what do you provide for the parameter `parentAlias`? Actually, parameter `parentAlias` is the parameter "[alias](https://github.com/Azure/open-service-broker-azure/blob/master/docs/modules/postgresql.md#provisioning-parameters-1)" when you create the DBMS **using the broker**. Currently there is no method to use use-provided postgre DBMS and create database on it using OSBA, but we will consider add this feature later.

And answer to your question 2: Unfortunately, I think there is no way to get rid of it, since abandoning instance in service catalog is not implemented yet: https://github.com/kubernetes-incubator/service-catalog/issues/2268. (I'm not very familiar with k8s, please correct me if I'm wrong. @krancour @jeremyrickard )

**Comment by zhongyi-zhang** [comment]
@norshtein for question 1: From the log, I think `parentAlias` was provided, therefore the provisioning request wasn't rejected. Instead, `azure-postgresql-9-6-dbms` with the corresponding `alias` was probably not created. So, the provisioning of this child service instance was held on to wait for the successful provisioning of its parent instance. @timwebster9 could you confirm it?

**Comment by norshtein** [comment]
Hi @zhongyi-zhang , according to the description "I've created an Azure PostgreSQL database server using azure CLI" , I guess that he was trying to use self-hosted DBMS and create database on it using OSBA, which is not supported by OSBA for postgreSQL, and thus the `parentAlias` is configured incorrectly.

I think we can estimate whether we should add `from-existing` services to PostgreSQL and Mysql just like in SQL.

**Comment by timwebster9** [comment]
> I guess that he was trying to use self-hosted DBMS and create database on it using OSBA

yes this is indeed what I doing

> If so, maybe our module doc doesn't describe the parent-child mechanism clearly.

I wouldn't disagree with that :-)

I tried provisioning the DBMS with OSBA, and then the instance on top of that and it worked fine 👍 .  It's not a problem for us to do it this way.  However I think it is a useful scenario to support using existing server, as we use a mix of provisioning methods which I imagine is a common scenario.

**Comment by norshtein** [comment]
Thanks for bringing that. For now, we have made it possible to use existing Azure SQL Server in OSBA, and we'll later investigate on Azure PostgreSQL and Azure MySQL.

**Comment by zhongyi-zhang** [comment]
Let's change the title and turn the issue to a feature request for using existing PostgreSQL.

**Comment by krancour** [comment]
Suggest creating a new issue for this that's just a feature request, absent the initial troubleshooting-- just helps to keep the thread focused.

**Comment by zhongyi-zhang** [comment]
@krancour it makes sense. I'll roll back the title and create a new issue.
