### ISSUE TITLE
Proposal: Add more experimental modules to OSBA

### ISSUE THREAD

**Issue by norshtein** [Azure/open-service-broker-azure#584]
Currently, OSBA provides several common-used services. I think, compared to [AWS Service Broker](https://github.com/awslabs/aws-servicebroker), we provide fewer services but with better support on existing services. Should we be more aggressive and add more experimental modules to OSBA? By adding more modules, we empower users to use more Azure services which they may be interested in. I have made a chart about the difference between AWS Service Broker and OSBA. And I'm glad to work on this if you think it's OK to add more experimental modules.

| **AWS Service Broker Services**    | **Corresponding Azure   Service**                            | **Is Provided by OSBA** |
| --------------------------- | ------------------------------------------------------------ | ----------------------- |
| Amazon Athena               | [Azure   Data Lake Analytics](https://azure.microsoft.com/services/data-lake-analytics/) | No                      |
| Amazon DynamoDB             | [Azure Cosmos DB](https://azure.microsoft.com/services/cosmos-db/) | Yes                     |
| Amazon ElastiCache          | [Azure   Redis Cache](https://azure.microsoft.com/services/cache/) | Yes                     |
| Amazon EMR                  | [HDInsight](https://azure.microsoft.com/services/hdinsight/) | No                      |
| Amazon Kinesis Data Streams | [Event Hubs](https://azure.microsoft.com/services/event-hubs/) | Yes                     |
| Amazon KMS                  | [Key   Vault](https://azure.microsoft.com/services/key-vault/) | Yes                     |
| Amazon Lex                  | [Bing   Speech API](https://azure.microsoft.com/services/cognitive-services/speech/) | No                      |
| Amazon Polly                | [Bing   Speech API](https://azure.microsoft.com/services/cognitive-services/speech/) | No                      |
| Amazon RDS for MariaDB      | Azure Database for MariaDB (preview)                         | No                      |
| Amazon RDS for MySQL        | [Azure   Database for MySQL](https://azure.microsoft.com/services/mysql/) | Yes                     |
| Amazon RDS for PostgreSQL   | [Azure Database for PostgreSQL](https://azure.microsoft.com/services/postgresql/) | Yes                     |
| Amazon Redshift             | [SQL   Data Warehouse](https://azure.microsoft.com/services/sql-data-warehouse/) | No                      |
| Amazon Rekognition          | [Computer   Vision API](https://azure.microsoft.com/services/cognitive-services/computer-vision/) | No                      |
| Amazon Route 53             | [Azure   DNS](https://azure.microsoft.com/services/dns/) & [Traffic   Manager](https://azure.microsoft.com/services/traffic-manager/) | No                      |
| Amazon S3                   | [Azure Storage—Block Blob (for   content logs, files) (Standard—Hot)](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/understanding-block-blobs--append-blobs--and-page-blobs#about-block-blobs) | Yes                     |
| Amazon SNS & SQS            | [Azure Service   Bus](https://azure.microsoft.com/en-us/services/service-bus/) | Yes                     |
| Amazon Translate            | [Translator   Text](https://azure.microsoft.com/en-us/services/cognitive-services/translator-text-api/) | No                      |

**Comment by norshtein** [comment]
Hi @rgardler , thanks for the suggestion. Going to close this issue and reopen it once more modules are required by our customers.

**Comment by timwebster9** [comment]
I've been asked about support for Azure PostgreSQL version 10.

Also Azure _Private_ DNS would definitely be useful, especially since GA is looming.  This would be useful in our scenario where we could map a DNS entry to the IP of the AKS service ILB IP address.

**Comment by tf04639** [comment]
_Azure for MariaDB_: I am not sure how hard can it be, but considering that at the driver level they are very similar, it should be "easy" to get support for _Azure for MariaDB_, maybe as a fork of the current MySQL stuff.

I don't know enough to provide patches, but in any other software projects I have been involved (including migration from dedicated, in house mysql servers to AWS RDS MariaDB instances) it's been been just a change in the connection string. I can imagine that the housekeeping tasks might be different, and Azure is not perfectly symmetrical. But still, if should be easy, right?

Very interested in this. Thank you very much for your work!
