### ISSUE TITLE
The Wordpress Helm chart used within this quickstart does not exist in azure helm repo.

### ISSUE THREAD

**Issue by jmlambert78** [Azure/open-service-broker-azure#593]
While testing the deployment of the osba for azure, I got the msg : 
**Error: Failed to fetch https://kubernetescharts.blob.core.windows.net/azure/wordpress-0.10.1.tgz : 404 The specified blob does not exist.**
I do not see who to get this chart ready to make a use of osba
THx

**Comment by jldeen** [comment]
+1 Can confirm same error. We just pushed the 0.10.1 release a few days ago. I will file an issue on the azure/wordpress repo. In the meantime, workaround is: to use `--version` flag with 0.10.0 release.
`helm install azure/wordpress --name osba-quickstart --namespace osba-quickstart --version 0.10.0`

**Comment by krancour** [comment]
This has been fixed. There was a bug in the newer version of the Dockerized toolset we use for publishing charts to Azure Storage. We've rolled back to the previous version of the toolset until the issue with those tools can be properly corrected.
