### ISSUE TITLE
Handling failures in the async engine?

### ISSUE THREAD

**Issue by arschles** [Azure/open-service-broker-azure#6]
_From @arschles on October 16, 2017 18:55_

I recall a discussion between myself and @krancour about handling failures in the async engine, in which we discussed rolling back changes that were made in prior steps. I believe the async engine doesn't have rollback support yet, but the best practice is to make steps idempotent which makes failure handling less important (because the steps can be re-run with minimal negative consequence). So, this issue exists to track discussion for whether we need to add support for:

1. Adding a "rollback" function to each step
2. Adding support in the async engine to rollback all successful steps before a failure

cc/ @krancour

**Comment by zhongyi-zhang** [comment]
Close as async engine was separated into its own project via https://github.com/Azure/open-service-broker-azure/pull/560.
