### ISSUE TITLE
Deprovisioning of postresqldatabase fails

### ISSUE THREAD

**Issue by denniszielke** [Azure/open-service-broker-azure#625]
Sometimes the deprovisioning of postgresqldatabase instances fails.
here some logs from the osba-open-service-broker-azure pod

time="2018-10-01T08:10:57Z" level=info msg="Open Service Broker for Azure starting" commit=ab0b831 version=v1.1.0
time="2018-10-01T08:10:57Z" level=info msg="Setting log level" logLevel=INFO
time="2018-10-01T08:10:57Z" level=info msg="Sensitive instance and binding details will be encrypted" encryptionScheme=AES256
time="2018-10-01T08:10:57Z" level=info msg="API server is listening with TLS enabled" address="https://0.0.0.0:8443"
time="2018-10-09T10:30:15Z" level=error msg="error executing job; not submitting any follow-up tasks" error="error executing deprovisioning step \"deletePostgreSQLDatabase\" for instance \"84fb8d0c-cb0c-11e8-a3cf-f6fabc5a7557\": error executing deprovisioning step: error deleting postgresql database: Long running operation terminated with status 'Failed': Code=\"InternalServerError\" Message=\"An unexpected error occured while processing the request. Tracking ID: '524d3341-746f-4228-9668-096dae10e004'\"" job=executeDeprovisioningStep taskID=5f2a99c9-3af4-461d-9424-13c5c2e58e7d
2018/10/09 10:31:38 http: TLS handshake error from 172.21.0.222:55146: EOF
2018/10/09 17:06:01 http: TLS handshake error from 172.21.0.222:40380: EOF
2018/10/09 21:12:37 http: TLS handshake error from 172.21.0.222:59836: read tcp 172.21.0.240:8443->172.21.0.222:59836: read: connection reset by peer
2018/10/09 23:54:04 http: TLS handshake error from 172.21.0.222:41698: EOF
2018/10/10 05:19:34 http: TLS handshake error from 172.21.0.222:43876: EOF
2018/10/10 08:07:51 http: TLS handshake error from 172.21.0.222:34250: EOF
2018/10/10 13:59:59 http: TLS handshake error from 172.21.0.222:55044: read tcp 172.21.0.240:8443->172.21.0.222:55044: read: connection reset by peer
2018/10/11 07:28:21 http: TLS handshake error from 172.21.0.222:56086: EOF
2018/10/11 11:09:49 http: TLS handshake error from 172.21.0.222:42332: read tcp 172.21.0.240:8443->172.21.0.222:42332: read: connection reset by peer
2018/10/12 00:54:07 http: TLS handshake error from 172.21.0.222:57356: read tcp 172.21.0.240:8443->172.21.0.222:57356: read: connection reset by peer
time="2018-10-12T07:26:18Z" level=error msg="error executing job; not submitting any follow-up tasks" error="error executing deprovisioning step \"deletePostgreSQLDatabase\" for instance \"7494d939-c8af-11e8-9873-f6fabc5a7557\": error executing deprovisioning step: error deleting postgresql database: Long running operation terminated with status 'Failed': Code=\"InternalServerError\" Message=\"An unexpected error occured while processing the request. Tracking ID: '4296ac38-b72b-40cf-b320-72003ad9306e'\"" job=executeDeprovisioningStep taskID=4534cb27-d25e-4dd8-96f8-82ef7f3d5a36
2018/10/12 11:37:52 http: TLS handshake error from 172.21.0.222:35088: read tcp 172.21.0.240:8443->172.21.0.222:35088: read: connection reset by peer
time="2018-10-12T12:11:58Z" level=error msg="error executing job; not submitting any follow-up tasks" error="error executing deprovisioning step \"deletePostgreSQLDatabase\" for instance \"0846b06b-cd63-11e8-b5ab-f6fabc5a7557\": error executing deprovisioning step: error deleting postgresql database: Long running operation terminated with status 'Failed': Code=\"InternalServerError\" Message=\"An unexpected error occured while processing the request. Tracking ID: '8a6505ce-bae4-468b-92f0-89072918a7d5'\"" job=executeDeprovisioningStep taskID=17ca6ef9-c85e-41be-a855-62f8cfade76a
2018/10/12 12:28:54 http: TLS handshake error from 172.21.0.222:55662: read tcp 172.21.0.240:8443->172.21.0.222:55662: read: connection reset by peer
2018/10/12 15:31:24 http: TLS handshake error from 172.21.0.222:56532: read tcp 172.21.0.240:8443->172.21.0.222:56532: read: connection reset by peer
2018/10/12 23:48:35 http: TLS handshake error from 172.21.0.222:35388: EOF
2018/10/13 10:44:49 http: TLS handshake error from 172.21.0.222:60986: EOF
2018/10/13 13:19:29 http: TLS handshake error from 172.21.0.222:33562: read tcp 172.21.0.240:8443->172.21.0.222:33562: read: connection reset by peer
2018/10/13 15:45:51 http: TLS handshake error from 172.21.0.222:47410: EOF
2018/10/13 21:32:18 http: TLS handshake error from 172.21.0.222:37838: read tcp 172.21.0.240:8443->172.21.0.222:37838: read: connection reset by peer
2018/10/14 02:01:12 http: TLS handshake error from 172.21.0.222:47684: read tcp 172.21.0.240:8443->172.21.0.222:47684: read: connection reset by peer
2018/10/14 03:21:08 http: TLS handshake error from 172.21.0.222:60772: read tcp 172.21.0.240:8443->172.21.0.222:60772: read: connection reset by peer
2018/10/14 10:16:34 http: TLS handshake error from 172.21.0.222:56646: read tcp 172.21.0.240:8443->172.21.0.222:56646: read: connection reset by peer
2018/10/15 03:55:20 http: TLS handshake error from 172.21.0.222:55058: EOF
time="2018-10-15T07:43:32Z" level=error msg="error executing job; not submitting any follow-up tasks" error="error executing provisioning step \"setupDatabase\" for instance \"de098b9b-d04d-11e8-a388-f6fabc5a7557\": error executing provisioning step: error starting transaction: pq: authentication failed for user \"postgres\": too many failed login attempts" job=executeProvisioningStep taskID=c8a69766-ae83-4239-8b10-5995cbdc7132
time="2018-10-15T07:43:56Z" level=error msg="error executing job; not submitting any follow-up tasks" error="error executing provisioning step \"setupDatabase\" for instance \"e5bdbf9d-d04d-11e8-a388-f6fabc5a7557\": error executing provisioning step: error starting transaction: pq: authentication failed for user \"postgres\": too many failed login attempts" job=executeProvisioningStep taskID=35e21e4c-a35c-4e62-886f-c8a83a4386ad
2018/10/15 09:00:48 http: TLS handshake error from 172.21.0.222:49364: read tcp 172.21.0.240:8443->172.21.0.222:49364: read: connection reset by peer
2018/10/15 17:24:13 http: TLS handshake error from 172.21.0.222:51430: EOF
2018/10/15 22:45:48 http: TLS handshake error from 172.21.0.222:48578: EOF
2018/10/16 05:14:39 http: TLS handshake error from 172.21.0.222:39304: read tcp 172.21.0.240:8443->172.21.0.222:39304: read: connection reset by peer
2018/10/16 05:54:07 http: TLS handshake error from 172.21.0.222:53316: read tcp 172.21.0.240:8443->172.21.0.222:53316: read: connection reset by peer

2.nd attempt

time="2018-10-16T11:45:21Z" level=info msg="Open Service Broker for Azure starting" commit=938c42e version=v1.2.0
time="2018-10-16T11:45:21Z" level=info msg="Setting log level" logLevel=DEBUG
time="2018-10-16T11:45:21Z" level=info msg="Sensitive instance and binding details will be encrypted" encryptionScheme=AES256
time="2018-10-16T11:45:21Z" level=info msg="API server is listening with TLS enabled" address="https://0.0.0.0:8443"
2018/10/16 11:46:42 http: TLS handshake error from 172.21.0.35:55006: remote error: tls: bad certificate
...
time="2018-10-16T11:56:19Z" level=debug msg="received deprovisioning request" instanceID=7494d939-c8af-11e8-9873-f6fabc5a7557
time="2018-10-16T11:56:19Z" level=debug msg="cannot deprovision instance in its current state" instanceID=7494d939-c8af-11e8-9873-f6fabc5a7557 status=DEPROVISIONING_FAILED

**Comment by jeremyrickard** [comment]
The root of this error looks like it is coming from:

> time="2018-10-12T07:26:18Z" level=error msg="error executing job; not submitting any follow-up tasks" error="error executing deprovisioning step "deletePostgreSQLDatabase" for instance "7494d939-c8af-11e8-9873-f6fabc5a7557": error executing deprovisioning step: error deleting postgresql database: Long running operation terminated with status 'Failed': Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '4296ac38-b72b-40cf-b320-72003ad9306e'"" job=executeDeprovisioningStep taskID=4534cb27-d25e-4dd8-96f8-82ef7f3d5a36


This error is coming back from the ARM layer, and we're assuming that we'll never be able to delete it again, so we mark it as _PROVISION_FAILED_. Once it's in that state, we won't even accept the deprovision requests. 

This is another one, looks like the user `postgres` got locked out. 

> time="2018-10-15T07:43:56Z" level=error msg="error executing job; not submitting any follow-up tasks" error="error executing provisioning step "setupDatabase" for instance "e5bdbf9d-d04d-11e8-a388-f6fabc5a7557": error executing provisioning step: error starting transaction: pq: authentication failed for user "postgres": too many failed login attempts" job=executeProvisioningStep taskID=35e21e4c-a35c-4e62-886f-c8a83a4386ad

We'll look into what additional retry logic we can add around those failures to make the experience on this a little better.

**Comment by digeler** [comment]
removing the finalizer solved the issue :
For each service and binding you want to remove you need to hash the finalizer token like this for example :
 
Here is example from my side :
 
kubectl edit servicebindings wordpress-wordpress-mysql-binding -n wordpress
 
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  creationTimestamp: 2018-10-23T08:54:42Z
  finalizers:
  - kubernetes-incubator/service-catalog  --->hash this part
  generation: 1
  labels:
    app: wordpress-wordpress
    chart: wordpress-0.10.1
    heritage: Tiller
    release: wordpress
  name: wordpress-wordpress-mysql-binding
  namespace: wordpress
  resourceVersion: "298"
  selfLink: /apis/servicecatalog.k8s.io/v1beta1/namespaces/wordpress/servicebindings/wordpress-wordpress-mysql-binding
  uid: 482c0e9d-d6a1-11e8-8126-6a93c690189c
spec:
  externalID: 482c0cb2-d6a1-11e8-8126-6a93c690189c
  instanceRef:
    name: wordpress-wordpress-mysql-instance
  secretName: wordpress-wordpress-mysql-secret
  userInfo:
    groups:
    - system:serviceaccounts
    - system:serviceaccounts:kube-system
    - system:authenticated
    uid: ""
    username: system:serviceaccount:kube-system:default
status:
  asyncOpInProgress: false
  conditions:
  - lastTransitionTime: 2018-10-23T08:59:58Z
    message: Binding cannot begin because referenced ServiceInstance "wordpress/wordpress-wordpress-mysql-instance"
      is not ready
    reason: ErrorInstanceNotReady
    status: "False"
    type: Ready
  orphanMitigationInProgress: false
  reconciledGeneration: 0
  unbindStatus: NotRequired
 
add a hash where I pointed in yellow and save by escape !wq
 
then :
kubectl delete servicebindings wordpress-wordpress-mysql-binding -n wordpress --force
 
this will remove the bindings.
 
Next do the same for the servicebindings :
 
kubectl edit serviceinstance  wordpress-wordpress-mysql-instance -n wordpress
 
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  creationTimestamp: 2018-10-23T08:54:42Z
  finalizers:
  - kubernetes-incubator/service-catalog -->hash this part
  generation: 1
  labels:
    app: wordpress-wordpress
    chart: wordpress-0.10.1
    heritage: Tiller
    release: wordpress
  name: wordpress-wordpress-mysql-instance
  namespace: wordpress
  resourceVersion: "299"
  selfLink: /apis/servicecatalog.k8s.io/v1beta1/namespaces/wordpress/serviceinstances/wordpress-wordpress-mysql-instance
  uid: 4831053f-d6a1-11e8-8126-6a93c690189c
spec:
  clusterServiceClassExternalName: azure-mysql-5-7
  clusterServiceClassRef:
    name: 997b8372-8dac-40ac-ae65-758b4a5075a5
  clusterServicePlanExternalName: general-purpose
  clusterServicePlanRef:
    name: eae202c3-521c-46d1-a047-872dacf781fd
  externalID: 483104df-d6a1-11e8-8126-6a93c690189c
  parameters:
    firewallRules:
    - endIPAddress: 255.255.255.255
      name: AllowAll
      startIPAddress: 0.0.0.0
    location: northeurope
    resourceGroup: wordpress
    sslEnforcement: disabled
  updateRequests: 0
  userInfo:
    groups:
    - system:serviceaccounts
    - system:serviceaccounts:kube-system
    - system:authenticated
    uid: ""
    username: system:serviceaccount:kube-system:default
status:
  asyncOpInProgress: false
  conditions:
  - lastTransitionTime: 2018-10-23T09:03:14Z
    message: The instance was provisioned successfully
    reason: ProvisionedSuccessfully
    status: "True"
    type: Ready
  deprovisionStatus: Required
  externalProperties:
    clusterServicePlanExternalID: eae202c3-521c-46d1-a047-872dacf781fd
    clusterServicePlanExternalName: general-purpose
    parameterChecksum: 5d170dcd1bb11ebaabbabce15e809736834a21283250b7ff02de700fefba9c04
    parameters:
      firewallRules:
      - endIPAddress: 255.255.255.255
 
Save and exit  then :
kubectl delete serviceinstance wordpress-wordpress-mysql-instance --force -n wordpress
 
use svcat to check that it is all removed.
 
dinorgeler@win10: local$svcat get bindings -n wordpress
 NAME   NAMESPACE   INSTANCE   STATUS
+------+-----------+----------+--------+
dinorgeler@win10: local$svcat get instance -n wordpress
  NAME   NAMESPACE   CLASS   PLAN   STATUS
