### ISSUE TITLE
Add Service Bus plan which includes queue/topic

### ISSUE THREAD

**Issue by luigibk** [Azure/open-service-broker-azure#632]
A Service Bus plan should be available in OSBA which includes the creation of a queue or a topic. Ideally such queue (or topic) could be named based on a parameter passed in by the user (not randomly).

**Comment by norshtein** [comment]
Thanks for the feedback. It's reasonable for OSBA to create a queue or a topic. I'll schedule to implement this. Does the feature is urgently needed? And, just like blob container, why a name is preferred for you?

**Comment by luigibk** [comment]
Thanks for replying. Queue/Topic creation is not urgently needed as I have a workaround, which is ugly but ok for now. 
A name is useful in all the situations when I want to create a replica of a specific environment for testing or other use.

**Comment by KevinJCross** [comment]
I'm just trying to write a helm template to create my service bus with a specific queue and access policies.

Is there any chance there is a timeline on this addition ?

**Comment by norshtein** [comment]
Hi all, now you are able to create queue and topic using latest OSBA. Your feedback is welcomed. **Caution**: the new feature causes a breaking changing in service bus module.
