### ISSUE TITLE
Add "blob-container-named" service plan to Storage

### ISSUE THREAD

**Issue by luigibk** [Azure/open-service-broker-azure#633]
It would be useful to have a service plan for Storage which allowed users to pass a container name as parameter. This would be similar to the currently available blob-container plan, but it would accept as parameter the container name (or better a list of container names) to be created.

**Comment by luigibk** [comment]
Hi @norshtein, in my specific case I need to be able to create a few containers inside the storage. To replicate the environment I am testing these containers would ideally have the same names as in the original environment. At the moment I do all this manually after OSBA has created the storage space. This works but I suspect it could be a common enough use case to be considered for an enhancement of OSBA.

**Comment by norshtein** [comment]
It makes sense. I'll add this enhancement.

**Comment by norshtein** [comment]
Hi @luigibk , this functionality has been added in recent refactoring in storage module, feel free to re-open the issue if you have any question.

**Comment by timja** [comment]
@norshtein would it be possible to create a list of blob containers and not just one?

**Comment by norshtein** [comment]
Hi @timja , currently not. That's because creating a list of blob container is not an "atomic" operation. Almost in every place, for example, Azure Portal, you can only create a single blob container, and we think OSBA should observe this rule too.

**Comment by timja** [comment]
Is there any work around using OSBA to create more than one?

**Comment by norshtein** [comment]
You may create an `azure-storage-blob-storage-account` instance and then create several `azure-storage-blob-container` instances upon it.
