### ISSUE TITLE
Empty schema returned for service binding creation and service instance updates

### ISSUE THREAD

**Issue by derberg** [Azure/open-service-broker-azure#634]
Hey,

I encountered as strange behaviour in the broker. Looks like it is returning for `schemas. service_binding.create` and `schemas.service_instance.update` the following object

```
{
            "$schema": "http://json-schema.org/draft-04/schema#",
            "additionalProperties": false,
            "type": "object"
}
```

I have one example, from the Service Catalog point of view (that consumes data from azure broker)

```
kubectl get clusterserviceplan 189d3b8f-8307-4b3f-8c74-03d069237f70 -n stage -o json
{
    "apiVersion": "servicecatalog.k8s.io/v1beta1",
    "kind": "ClusterServicePlan",
    "metadata": {
        "creationTimestamp": "2018-11-09T00:55:15Z",
        "name": "189d3b8f-8307-4b3f-8c74-03d069237f70",
        "ownerReferences": [
            {
                "apiVersion": "servicecatalog.k8s.io/v1beta1",
                "blockOwnerDeletion": false,
                "controller": true,
                "kind": "ClusterServiceBroker",
                "name": "core-azure-broker",
                "uid": "1732a5b8-e3ba-11e8-ac4a-26baf1444948"
            }
        ],
        "resourceVersion": "71",
        "selfLink": "/apis/servicecatalog.k8s.io/v1beta1/clusterserviceplans/189d3b8f-8307-4b3f-8c74-03d069237f70",
        "uid": "1ec4c303-e3ba-11e8-ac4a-26baf1444948"
    },
    "spec": {
        "clusterServiceBrokerName": "core-azure-broker",
        "clusterServiceClassRef": {
            "name": "2e2fc314-37b6-4587-8127-8f9ee8b33fea"
        },
        "description": "A specialized Azure storage account for storing block blobs and append blobs; automatically provisions a blob container  within the account",
        "externalID": "189d3b8f-8307-4b3f-8c74-03d069237f70",
        "externalMetadata": {
            "bullets": [
                "A specialized Azure storage account for storing block blobs and append blobs",
                "Automatically provisions a blob container within the account"
            ],
            "displayName": "Blob Container"
        },
        "externalName": "blob-container",
        "free": false,
        "instanceCreateParameterSchema": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "additionalProperties": false,
            "properties": {
                "location": {
                    "description": "The Azure region in which to provision applicable resources.",
                    "title": "Location",
                    "type": "string"
                },
                "resourceGroup": {
                    "description": "The (new or existing) resource group with which to associate new resources.",
                    "title": "Resource group",
                    "type": "string"
                }
            },
            "required": [
                "location",
                "resourceGroup"
            ],
            "type": "object"
        },
        "instanceUpdateParameterSchema": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "additionalProperties": false,
            "type": "object"
        },
        "serviceBindingCreateParameterSchema": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "additionalProperties": false,
            "type": "object"
        }
    },
    "status": {
        "removedFromBrokerCatalog": false
    }
}
```

Now, my question is, is it a bug or is it a standard way of handling schemas? This is not so much clear for me. From the OSBA spec point of view `parameters` field is not mandatory https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#input-parameters-schema-object and for me it means you provided it only in case you have meaningfull data.

Now, why I'm asking. It has a certain impact on a frontend layer. In case of your broker frontend gets information that there is a schema provided and displays user proper functionality, but at the end it is empty as schema has no meaningful data. Sure you can say, `just make your UI resilient` but it must be resilient to all the brokers in general, not just Azure, and the object you return:
```
{
            "$schema": "http://json-schema.org/draft-04/schema#",
            "additionalProperties": false,
            "type": "object"
}
```
Is it a standard of defining empty json schemas?

**Comment by zhongyi-zhang** [comment]
Got the point.
I think this is caused by that, https://github.com/Azure/open-service-broker-azure/blob/master/pkg/service/catalog.go#L81 the `schema` field doesn't use a pointer. So `omitempty` doesn't work when it is empty.
@krancour @jeremyrickard what do you think, should we do the change?

**Comment by zhongyi-zhang** [comment]
I tried to do some refactor. On the other hand, I rethought about the problem. The object just like which you quoted 
```
{
            "$schema": "http://json-schema.org/draft-04/schema#",
            "additionalProperties": false,
            "type": "object"
}
```
does be a standard. It is not totally meaningless. By the empty schemas, the broker explicitly clarifies that "this operation doesn't support any parameters". So in my opinion, the return is expected. Does it make sense?

**Comment by derberg** [comment]
@zhongyi-zhang but is this a standard way/approach. When I did my research I haven't found any standard that describes how the empty schema should look like, in one feed it was:
```
{ 
   "description": "voice mail record", 
   "type": "object", 
   "additionalProperties": false, 
   "properties": { 
    } 
  } 
} 
```

the difference is not big. What would be your advice, how to validate if schema is empty? two conditions? **additionalProperties** set to `false` AND/OR empty **properties** ? and in case if I have **$ref** or root I resolve it first and then validate what it contains?

**Comment by zhongyi-zhang** [comment]
@derberg if the frontend layer is wrote in a language which has zero values for variables as initial values, the parser can get the same result no matter there is a `"properties": {}`, e.g. Go: https://play.golang.org/p/GtIofhYHPbz. If not, I think it is okay to deal with two conditions or set zero values for empty fields.

**Comment by derberg** [comment]
Ok, I'll take it from here, we need to secure from such scenarios for future anyway because validators will still pass it through, thanks a lot for your comments
