### ISSUE TITLE
Add support for IoT hub

### ISSUE THREAD

**Issue by luisdavim** [Azure/open-service-broker-azure#635]
Hi,

would it be possible to add support for IoT Hub?

**Comment by norshtein** [comment]
Thanks for raising that. I'll do this.

**Comment by norshtein** [comment]
Hi @luisdavim , I had a quick look on IoT hub and designed the usage of module, please have a look whether it meet your requirement:

**Provision**: provisions a IoT hub 
##### Provision parameters:
  - resourceGroupName
  - region
  - sku_name, string, for example, "S1"
  - sku_units, integer, for example, 1

**Bind**: return the connection string of the IoT hub, that's something like `HostName=<generated_username>.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=<access_key>`

**Unbind**: does nothing

**Deprovision**: delete the IoT hub

**Comment by luisdavim** [comment]
Looks good to me. Thanks

**Comment by luisdavim** [comment]
I think this is a good reference of what is needed https://www.terraform.io/docs/providers/azurerm/r/iothub.html
