### ISSUE TITLE
Convert "location" string property to enum in JSON schema

### ISSUE THREAD

**Issue by pkosiec** [Azure/open-service-broker-azure#655]
**Description**
Currently, the `location` property in schemas of various Service Plans, like Basic Tier plan for Azure Database for MySQL 5.7, is defined as simple `string` property. However, using `enum` in this case would be a huge improvement for usability in rendering the JSON schema as UI form.

It is related to JSON schema rendering on UI, similar to #651 and #519.

**Example**
Basic Tier plan for Azure Database for MySQL 5.7

As this is a simple `string` property, user has to type the location manually:

<img width="680" alt="screen shot 2018-12-18 at 10 07 41" src="https://user-images.githubusercontent.com/7155799/50143456-f46e2380-02ac-11e9-841b-af6a5bdf4a66.png">

**Expected result**
Beta plan for "Cloud SQL - MySQL" Service Class (Google Cloud Platform Broker)

As this is `enum`, it renders as convenient select box:

<img width="688" alt="screen shot 2018-12-18 at 09 33 20" src="https://user-images.githubusercontent.com/7155799/50142886-79f0d400-02ab-11e9-80c4-96f1fb1fd37b.png">
<img width="699" alt="screen shot 2018-12-18 at 09 33 25" src="https://user-images.githubusercontent.com/7155799/50142887-79f0d400-02ab-11e9-935a-3d19afe26ce9.png">

**Comment by norshtein** [comment]
Hi @pkosiec , thanks for raising this! This proposal looks pretty good to us. Could you give us an example JSON object so that we can refactor our code?

**Comment by pkosiec** [comment]
Hi @norshtein,

Sure thing. Instead of the following `location` property object:

```json
{
    "location": {
      "description": "The Azure region in which to provision applicable resources.",
      "title": "Location",
      "type": "string"
    }
}
```

I would like to see this one:

```json
{
  "location": {
    "default": "",
    "enum": [
      "eastasia", "southeastasia", "centralus", "eastus", "eastus2", "westus", "northcentralus", "southcentralus", "northeurope", "westeurope", "japanwest", "japaneast", "brazilsouth", "australiaeast", "australiasoutheast", "southindia", "centralindia", "westindia", "canadacentral", "canadaeast", "uksouth", "ukwest", "westcentralus", "westus2", "koreacentral", "koreasouth", "francecentral", "francesouth", "australiacentral", "australiacentral2"
    ],
    "description": "The Azure region in which to provision applicable resources.",
    "title": "Location",
    "type": "string"
  }
}

```

I don't know if I included all available locations, but anyway, here's the general concept how it could look like 🙂

**Comment by norshtein** [comment]
Hi @pkosiec , the example does make sense. OSBA will apply this change soon.

**Comment by derberg** [comment]
@norshtein Hey, thanks a lot for such rapid activity in those issues that Pawel reported.

Could you explain what you mean in statement that `OSBA will apply this change soon` ? What OSBA has to do with that? OSBA only requires the broker provider to specify a valid v4 json schema  https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#input-parameters-schema-object so both usaceses on providing enum as array of strings or array of objects as part of `oneOf` are valid as they are valid with Json Schema. Or I'm totally missing something and I apologize in advance 🙈

**Comment by derberg** [comment]
Interesting, @norshtein OSBA is for you Open Service Broker API or Open Service Broker Azure 😄

**Comment by pkosiec** [comment]
@derberg The official abbreviation of Open Service Broker API is **OSBAPI** (search for it here: https://www.openservicebrokerapi.org/ or on https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md), and abbreviation of Open Service Broker for Azure is **OSBA** (search for OSBA on main readme: https://github.com/Azure/open-service-broker-azure).

Case solved 😄

**Comment by norshtein** [comment]
Hi @derberg , my OSBA in previous comment means Open Service Broker Azure. What @pkosiec said is correct.
