### ISSUE TITLE
Cloud Foundry Service Broker Setup

### ISSUE THREAD

**Issue by robdickens** [Azure/open-service-broker-azure#656]
Hi,

I have deployed the service broker app for cloud foundry following the tutorial however I am having an issue at the end of the tutorial running:

`cf create-service-broker open-service-broker-azure username password https://osba.apps.example.com`

I get the following meesage:

`Schema service_instance.create.parameters is not valid. Must conform to JSON Schema Draft 04`

To check everything works, I've run:

`curl -u <username>:<password> http://<hostname>/v2/catalog --header "X-Broker-API-Version: 2.13"`

and I do get the service list back, but it won't let me create the service broker.

I'm running cf version 6.39.0+607d4f8be.2018-09-11

Is this an issue with the osba app are something I'm doing wrong?

**Comment by norshtein** [comment]
Thanks for bringing up the issue! It's a bug in OSBA. We have found where the problem locates and a hotfix will be released soon.

**Comment by norshtein** [comment]
Hi @robdickens , you now should be able to install OSBA using release [v1.3.1](https://github.com/Azure/open-service-broker-azure/releases/tag/v1.3.1). Sorry for the inconvenience!

**Comment by robdickens** [comment]
@norshtein thank you for the quick turnaround!
