### ISSUE TITLE
Respond with error message if operation fails

### ISSUE THREAD

**Issue by zhongyi-zhang** [Azure/open-service-broker-azure#66]
For example: I didn't specified location in provisioning parameters, it would return:
<pre>
$ cf create-service azure-sqldb basic sqlsql
Creating service instance sqlsql in org IP.xip.io_ORGANIZATION / space azure as admin...
FAILED
Server error, status code: 502, error code: 10001, message: The service broker rejected the request to http://asb.IP.xip.io/v2/service_instances/ace140b2-79dc-4ed3-bacb-c4eba0eb67dc?accepts_incomplete=true.
<b>Status Code: 400 Bad Request, Body: {}</b>
</pre>
Relative line:
https://github.com/Azure/azure-service-broker/blob/master/pkg/api/provision.go#L225

See bold, user only knows that it is a bad request but what's the reason in details? User needs to use `cf logs asb --recent` to find out that.
At worst, some other polling operations are working at the same time, maybe it's a little hard to find the corresponding error message. (PS, such an error is printed to stdout, is it expected?)
<pre>
2017-11-17T02:03:31.02+0000 [APP/PROC/WEB/0] <b>OUT</b> time="2017-11-17T02:03:31Z" level=debug msg="bad provisioning request: validation error" field=location instanceID=ace140b2-79dc-4ed3-bacb-c4eba0eb67dc issue="invalid location: \"\""
</pre>

Anyway, it's better to always respond with error message if operation failed.

**Comment by carolynvs** [comment]
👍  I ran into this as well. This is the catalog response I get when forgetting to set a required param:

```json
{
      "metadata": {
        "name": "noparams",
        "namespace": "default",
        "selfLink": "/apis/servicecatalog.k8s.io/v1beta1/namespaces/default/serviceinstances/noparams",
        "uid": "d4d93910-e509-11e7-926b-0242ac110006",
        "resourceVersion": "1214",
        "generation": 1,
        "creationTimestamp": "2017-12-19T22:13:24Z",
        "finalizers": [
          "kubernetes-incubator/service-catalog"
        ]
      },
      "spec": {
        "clusterServiceClassExternalName": "azure-mysqldb",
        "clusterServicePlanExternalName": "standard800",
        "clusterServiceClassRef": {
          "name": "997b8372-8dac-40ac-ae65-758b4a5075a5"
        },
        "clusterServicePlanRef": {
          "name": "08e4b43a-36bc-447e-a81f-8202b13e339c"
        },
        "parameters": {},
        "externalID": "cc138095-0826-49a9-a739-023a8666e2b9",
        "updateRequests": 0
      },
      "status": {
        "conditions": [
          {
            "type": "Ready",
            "status": "False",
            "lastTransitionTime": "2017-12-19T22:13:25Z",
            "reason": "ProvisionCallFailed",
            "message": "ClusterServiceBroker returned a failure for provision call; operation will not be retried: Error provisioning ServiceInstance of ClusterServiceClass (K8S: \"997b8372-8dac-40ac-ae65-758b4a5075a5\" ExternalName: \"azure-mysqldb\") at ClusterServiceBroker \"osba\": Status: 400; ErrorMessage: \u003cnil\u003e; Description: \u003cnil\u003e; ResponseError: \u003cnil\u003e"
          },
          {
            "type": "Failed",
            "status": "True",
            "lastTransitionTime": "2017-12-19T22:13:25Z",
            "reason": "ClusterServiceBrokerReturnedFailure",
            "message": "Error provisioning ServiceInstance of ClusterServiceClass (K8S: \"997b8372-8dac-40ac-ae65-758b4a5075a5\" ExternalName: \"azure-mysqldb\") at ClusterServiceBroker \"osba\": Status: 400; ErrorMessage: \u003cnil\u003e; Description: \u003cnil\u003e; ResponseError: \u003cnil\u003e"
          }
        ],
        "asyncOpInProgress": false,
        "orphanMitigationInProgress": false,
        "reconciledGeneration": 1,
        "deprovisionStatus": "Required"
      }
    },
```

Side Note: What's up with all the odd characters (`\u003`) coming back in the message?
