### ISSUE TITLE
jdbcUrl for postgres 

### ISSUE THREAD

**Issue by olevett** [Azure/open-service-broker-azure#662]
The MSSQL service provides a jdbcUrl property to the secret (e.g. [here](https://github.com/Azure/open-service-broker-azure/blob/ac21045a8e25fc64f1b3b03a88a3660c91517cc8/pkg/services/mssqldr/common_types.go#L11), which is missing from the MySQL/postgres services.

Is there a reason for this inconsistency, or would a PR for adding JDBC URLs to the other DBs be useful?

**Comment by jeremyrickard** [comment]
PR would be welcome!

**Comment by zhongyi-zhang** [comment]
Solved by https://github.com/Azure/open-service-broker-azure/pull/698.
