### ISSUE TITLE
Icons are no longer valid

### ISSUE THREAD

**Issue by arapulido** [Azure/open-service-broker-azure#666]
Icons for the classes are pointing to https://azure.microsoft.com/svghandler/postgresql/?width=200 which doesn't seem to be valid anymore

**Comment by zhongyi-zhang** [comment]
Thank you for reporting this. I am going to fix it soon.

**Comment by PK85** [comment]
Hello @zhongyi-zhang,

When do you plan to release that change?

Cheers, Piotr

**Comment by zhongyi-zhang** [comment]
@PK85 expected to be tomorrow!
