### ISSUE TITLE
Azure Service Broker Icon images missing in OpenShift Service Catalog 

### ISSUE THREAD

**Issue by alberttwong** [Azure/open-service-broker-azure#668]
![screen shot 2019-01-29 at 4 01 19 pm](https://user-images.githubusercontent.com/749093/51948916-3f687400-23df-11e9-9dd8-eb67697eb4c2.png)

**Comment by zhongyi-zhang** [comment]
Duplicated with https://github.com/Azure/open-service-broker-azure/issues/666, closed.
