### ISSUE TITLE
purge DeprovisionCallFailed entries from database

### ISSUE THREAD

**Issue by cforce** [Azure/open-service-broker-azure#682]
I have the issue that i have left overs from DeprovisionCallFailed or Failed. How can i force to remove such entries (and accept i might handle the deprovisioning manually)
Can't find an svcat cmd/param (line in "cf purge-service-instance mysql-dev")  that allows to force delete the entries .

**Comment by zhongyi-zhang** [comment]
Yeah, svcat has not force delete so far: https://github.com/kubernetes-incubator/service-catalog/issues/2268. You can manually delete the stuck instance record from OSBA store (the redis cache). Then, use svcat to deprovision again. OSBA returns 410 in this case and svcat considers it as a success. And then don't forget to delete the ARM resource from Portal.

**Comment by cforce** [comment]
Looks like merg for solution has beedn done on incibator
https://github.com/kubernetes-incubator/service-catalog/pull/2579

**Comment by zhongyi-zhang** [comment]
Solved by service-catalog as @cforce mentioned.
