### ISSUE TITLE
Only stable services are visible on Openshift catalog

### ISSUE THREAD

**Issue by Mekkatorque** [Azure/open-service-broker-azure#684]
Followed the instructions for installing the Open Service Broker for Azure on Openshift via the template. Installation worked perfectly without errors. Azure Service Broker is visible with `oc get clusterservicebrokers`. 
However, although the [template yaml](https://raw.githubusercontent.com/Azure/open-service-broker-azure/master/contrib/openshift/osba-os-template.yaml) file has `MIN_STABILITY=EXPERIMENTAL` only the stable services are visible/available.

**Comment by zhongyi-zhang** [comment]
The OSBA version in this template is a hard coded old version `image: microsoft/azure-service-broker:v1.0.1`. You can modify it.

**Comment by Mekkatorque** [comment]
Tnx, apparantly, I must have missed that one. Worked perfectly when changing the version within the template to `image: microsoft/azure-service-broker:latest`.
