### ISSUE TITLE
Question: is there a way to discover the created Event Hub name when provisioning the Event Hub

### ISSUE THREAD

**Issue by jakkaj** [Azure/open-service-broker-azure#685]
Problem: Creating an Event Hub ServiceInstance appears to need an extra step to discover the created Event Hub name. The broker/secret returns the namespace connection string and primary key, but it does not provide the child Event Hub itself. 

The event hub name is a randomly generated GUID [here](https://github.com/Azure/open-service-broker-azure/blob/7be26814e9a5482b3a590a74ad0b629566bede30/pkg/services/eventhubs/provision.go#L26), so it's not possible to guess/use convention. 

It might be nice if the broker output the generated hub name [here](https://github.com/Azure/open-service-broker-azure/blob/7be26814e9a5482b3a590a74ad0b629566bede30/pkg/services/eventhubs/bind.go#L19)

Am I missing something?

Cheers!

Jordan.

**Comment by zhongyi-zhang** [comment]
Yeah, [binding](https://github.com/Azure/open-service-broker-azure/blob/master/pkg/services/eventhubs/bind.go) doesn't deliver the hub name though provisioning creates the hub...
As far as I know, all the OSBA maintainers are busy with other projects now. Super appreciate your PR on this!
