### ISSUE TITLE
Template for Openshift is not compatible with current Openshift OKD deployment template.

### ISSUE THREAD

**Issue by sjyang18** [Azure/open-service-broker-azure#687]
Current Openshift OKD deployment is 3.9 and installing OSBA template on it would result in the failure in provisioning. Looking at the template, OSBA version is hard-coded and is v1.0.1, which is the reason why it is not compatible.

 I verified OSBA v1.5.0 would work on the current Openshfit OKD (3.9) deployment template. 

https://raw.githubusercontent.com/Azure/open-service-broker-azure/master/contrib/openshift/osba-os-template.yaml should be modified to receive a parameter so that user may override the OSBA version.

I have created a patch and tested locally:  https://raw.githubusercontent.com/sjyang18/open-service-broker-azure/sjyang18-patch-1/contrib/openshift/osba-os-template.yaml 

I will submit the pull request shortly.

**Comment by zhongyi-zhang** [comment]
Closed by your PR https://github.com/Azure/open-service-broker-azure/pull/688. Thanks :).
