### ISSUE TITLE
Are there plans for services like Azure Application Gateway to be supported?

### ISSUE THREAD

**Issue by erick-thompson** [Azure/open-service-broker-azure#689]
I've noticed that most of the resources available using the OSBA are application services, which is awesome and incredibly useful. Are there plans to support services that are more "infrastructure" like such as Azure Application Gateway, Azure Traffic Manager, etc?

I am planning to use Azure Application Gateway to handle SSL termination and take advantage of the Web application firewall for AKS based services. In addition, I am planning to use Azure Traffic Manager for regional fail-over.

I'm using Istio, so using the Azure Application Gateway ingress controller isn't possible.

**Comment by zhongyi-zhang** [comment]
No, there is no plan for App Gateway. I had some experience about it. The settings like "backend pools", "listeners", "rules", "health probes" are too many and complicated. It seems to me that neither configuring nor debugging by using a broker couldn't be a good experience, isn't it?
