### ISSUE TITLE
Add API key binding to Application Insights

### ISSUE THREAD

**Issue by kyschouv** [Azure/open-service-broker-azure#702]
To be able to access application insights from Grafana, we need an API key. It would be awesome if this could be provisioned with the App Inisghts resource through osba, rather than having to write something separate to create and manage it.

**Comment by zhongyi-zhang** [comment]
I am happy to do adding this. But I hit an issue deleting API key with Azure Go SDK in unbinding. Tracking https://github.com/Azure/azure-sdk-for-go/issues/4993.

**Comment by kyschouv** [comment]
Thanks for the quick resolution! When's the next release scheduled?

**Comment by zhongyi-zhang** [comment]
Here it is! https://github.com/Azure/open-service-broker-azure/releases/tag/v1.7.0

**Comment by kyschouv** [comment]
Thanks! Should I wait for the new helm chart, or is it safe to just upgrade the image version from 1.6.0 to 1.7.0?

**Comment by zhongyi-zhang** [comment]
A new chart was also published in our release pipeline. Feel free to have a try:). Feedback is welcome.

**Comment by kyschouv** [comment]
Excellent! Deployed fine! Is there a way to update current bindings, or do I need to redeploy those?

**Comment by zhongyi-zhang** [comment]
Yes, please delete the old instances and create a new one. Because the PR brings into appID as a new property in store. Binding for the old instances can't find it and would fail.
