### ISSUE TITLE
The osba not support chinaeast2 region

### ISSUE THREAD

**Issue by pengzhisun** [Azure/open-service-broker-azure#704]
Based on the osba helm chart values.yaml schema, I could config the azure.environment parameter to AzureChinaCloud, but while creating a service instance for mysql in aks (mooncake), I got the following error message:

Warning  ProvisionCallFailed                  4s (x3 over 3m33s)  service-catalog-controller-manager  Error provisioning ServiceInstance of ClusterServiceClass (K8S: "997b8372-8dac-40ac-ae65-758b4a5075a5" ExternalName: "azure-mysql-5-7") at ClusterServiceBroker "osba": Status: 400; ErrorMessage: ValidationError; Description: The value provided for location is invalid: field value is invalid; ResponseError: <nil>

And after searched in this repository with other supported region like 'westus2', I found the following location related files not including 'chinaeast2' region:

https://github.com/Azure/open-service-broker-azure/blob/master/pkg/azure/locations.go
https://github.com/Azure/open-service-broker-azure/blob/master/pkg/schemas/location_schema.go

Do you have plan to support the OSBA in Azure Mooncake regions? Since the AKS is ready GA in mooncake, the stable supported services should be worked in mooncake too.

The values.yaml files for osba and wordpress sample chart as attached.

[osba_values.yaml.txt](https://github.com/Azure/open-service-broker-azure/files/3298066/osba_values.yaml.txt)
[wp_values.yaml.txt](https://github.com/Azure/open-service-broker-azure/files/3298067/wp_values.yaml.txt)

**Comment by zhongyi-zhang** [comment]
Resolved by https://github.com/Azure/open-service-broker-azure/pull/706.
