### ISSUE TITLE
Kubernetes Operator for OSBA?

### ISSUE THREAD

**Issue by alberttwong** [Azure/open-service-broker-azure#729]
Are there plans for a kubernetes operator for OSBA? https://kubernetes.io/docs/concepts/extend-kubernetes/operator/

**Comment by zhongyi-zhang** [comment]
Service operator? Yes. But the GitHub repo is private for now. I don't know when it will come to public.

**Comment by sakthi-vetrivel** [comment]
Do you have an idea of what sort of functionality you would want in a Kubernetes operator?

**Comment by sakthi-vetrivel** [comment]
@alberttwong The Azure Service Operator project is now public at https://github.com/Azure/azure-service-operator.
