### ISSUE TITLE
Enable Service Binding secrets to be stored in Azure Key vault

### ISSUE THREAD

**Issue by Sudharma** [Azure/open-service-broker-azure#736]
The Service Binding creates the secret in the Kubnernetes cluster.  It would be great idea if the secrets can be stored into the azure key vault. We are using one of the options for secret creation from here --> https://github.com/SparebankenVest/azure-key-vault-to-kubernetes .

**Comment by sakthi-vetrivel** [comment]
@Sudharma I'd recommend checking out https://github.com/Azure/azure-service-operator which has an option to store these connection strings in Key Vault.
