### ISSUE TITLE
Status of the repository

### ISSUE THREAD

**Issue by r-t-m** [Azure/open-service-broker-azure#740]
As all technologies relevant to Kubernetes getting stale fast and constantly need to keep up with new features/deprecations in newer k8s versions I as a user would like to understand the future state of this repository: are there any plans to continue to actively maintain and support it by maintainers/Microsoft, or any successors to OSBA (if any) should be considered instead?

The reason for this issue - there are no new PRs getting reviewed/accepted in almost half a year, even a simple ones.

**Comment by sakthi-vetrivel** [comment]
@r-t-m This project is no longer being maintained by Microsoft. As we’ve seen momentum in the Kubernetes community going from Open Service Broker to operators, we have decided to shift and consolidate our investments accordingly to support Azure services through operators instead. You can check out the Azure Service Operator project here: [https://aka.ms/azure-service-operator](aka.ms/azure-service-operator).

**Comment by IvanJosipovic** [comment]
Thank you for the update, it might be worthwhile to update the Readme. I was not aware that the Azure-Service-Operator existed until now :)

**Comment by sakthi-vetrivel** [comment]
Will do. Thanks!
