### ISSUE TITLE
Proposal: return instance schemas and binding schemas in catalog

### ISSUE THREAD

**Issue by Haishi2016** [Azure/open-service-broker-azure#93]
Although it's not mandated by the spec, I think we should return instance schema and binding schema in catalog so that a downstream service (like a catalog service) can discover how to construct proper provisioning/binding requests. There are currently no way for such services to discover how to make such requests. IMHO schemas should have been mandatory fields in the spec.

**Comment by carolynvs** [comment]
FYI, we are going to start showing these values in svcat, and it would be great if osba supported it. As otherwise I'm not sure how you would even know what to pass in.

https://github.com/kubernetes-incubator/service-catalog/issues/1720

**Comment by krancour** [comment]
> As otherwise I'm not sure how you would even know what to pass in.

Not the ideal answer, but there is documentation for each service. Just wanted you to know there's _something_.

**Comment by carolynvs** [comment]
Yeah... As I was developing svcat, the best way to figure out params was reading our own helm charts. I never found the real doc, so ... if we have it, it's not easy enough to find.
